### ISSUE TITLE
"Expected values" validator example

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/goodtables-py#10]
# Flow
## Receive data
- Client provides one of either:
  - A file object
  - A stream (known to be CSV)
- Client provides a configuration object
## Prepare for analysis
- If received configuration object, configure accordingly
- If received probes that do not match the CSV, throw and say why
## Make analysis
- Probe values based on config
  - This could be extended considerably. I'm suggesting a very simple set of rules for first pass (see config)
## Return report
- Respond with a report, which is a JSON object, like:
  - name (of file, or stream, or whatever)
  - config: the passed on config for this run
  - results:
    - per row: array of rows that have any deviations, with the deviation shown
    - per dataset: array of probe rules, and results of each probe
    - description: (eg: the CSV is valid according to probe because...)
# Implementation
## Code
- Based on examples here: https://github.com/Stiivi/brewery/blob/master/brewery/probes.py
- Suggest that first implementation is only for NULL check, and within range check
  - Thought: this really should be done alongside schema - e.g.: only check for number range if field is a valid field for numbers?
## Configuration
- Exit early (first value outside of probe conditions)
- A rules object with probing conditions. Ideas from discussion on labs list with Friedrich:
  - Each rule applies to a column
    - Check if values in column are not NULL
    - Check that values in column are within X range (e.g.: 10,000 <-> 25,000)
    - For each probe, set a detection strategy:
      - true/false (each row should comply)
      - weighted: e.g.: warn of more than 5% of data outside condition

**Comment by roll** [comment]
@pwalsh 
Not sure do we have to do something here. For now marking `done-in-next`. Or need more context)

**Comment by pwalsh** [comment]
Well, this is covered in next the same way it is covered in current- you can write a processor for the logic and inject it into the processing pipeline.

There is no need to do anything more at this stage, but I want to leave this open on the backlog.

**Comment by roll** [comment]
@pwalsh 
Thanks.

**Comment by pwalsh** [comment]
@roll how about you add an example processor to your examples (or, we could ship a contrib module), that just demonstrates this type of concept. then we can close this.

Here is an example: Alert if if values in a column of numbers or integers have a deviation of over, say, +/- 20% form the mean. 

Is that a hard one, as it is table based? it would be really cool.

**Comment by roll** [comment]
Heh - I had exactly the same idea but had no full understanding of what "expected values" means (and other stuff with config, probes etc). I suppose we should try to write an example for it (and then a tutorial).

**Comment by pwalsh** [comment]
yes. I was just thinking, if you can write an example like this in code, then we can follow up with some blog posts on customisation with good tables.

**Comment by pwalsh** [comment]
Closing in favour of https://github.com/frictionlessdata/goodtables-py/issues/191
