### ISSUE TITLE
CSV is not being parsed correctly and GT crashes analysing it

### ISSUE THREAD

**Issue by cecilaki** [frictionlessdata/goodtables-py#100]
Trying to validate this file (for further import on OS) but don't see what's wrong in it and GT doesn't help.

[PEF2016_AC01.csv.zip](https://github.com/frictionlessdata/goodtables/files/268161/PEF2016_AC01.csv.zip)

**Comment by akariv** [comment]
Seems like character encoding detection did not work correctly on this file, finding 'utf-8' instead of the correct 'iso-8859-1' (or 'windows-1252')

**Comment by georgiana-b** [comment]
The file encoding is indeed `ISO-8859-1` but it's detected as `ISO-8859-2` because [_chardet_ does not support `ISO-8859-1`](https://pypi.python.org/pypi/chardet). On the plus side, this does not affect how the file is parsed so I'll work on solving that.

**Comment by akariv** [comment]
windows-1252 is a superset of ISO-8859-1. It should have detected that...

**Comment by georgiana-b** [comment]
@akariv [This](http://chardet.readthedocs.io/en/latest/how-it-works.html#windows-1252) gives some insight on that.

**Comment by akariv** [comment]
Yes, it's sort of the default, so we need to understand what went wrong.

> windows-1252, which is used primarily on Microsoft Windows; its subset, ISO-8859-1 is widely used for legacy 8-bit-encoded text. chardet, like many encoding detectors, defaults to guessing this encoding when no other can be reliably established.


**Anyway**,
I tried to analyze the entire file with `chardet`, and this is what it returned after 5min of processing:
```
In [56]: chardet.detect(open('/Users/adam/Downloads/PEF2016_AC01.csv').read())
Out[56]: {'confidence': 0.8630475235351392, 'encoding': 'ISO-8859-2'}
```

Then I found out about `cchardet`, which is a re-implementation of chardet with c-bindings. I returns this in a fraction of a second:
```
In [2]: cchardet.detect(open('/Users/adam/Downloads/PEF2016_AC01.csv').read())
Out[2]: {'confidence': 0.9900000095367432, 'encoding': u'WINDOWS-1252'}
```

So I think we should probably move to using `cchardet` as well (it's being used by others too, e.g. BeautifulSoup). 
@pwalsh wdyt?

**Comment by georgiana-b** [comment]
I have tested several encodings with `cchardet` and I confirm it performs better.

**Comment by pwalsh** [comment]
@roll if this acts correctly in v1 I am happy to close this.

**Comment by roll** [comment]
```bash
goodtables table tmp/issue100.csv
DATASET
=======
{'error-count': 0, 'table-count': 1, 'time': 0.124, 'valid': True}

TABLE [1]
=========
{'error-count': 0,
 'headers': ['Ciclo',
             'Ramo',
             'RAMO_DESCRIPCION',
             'UNIDAD',
             'UNIDAD_DESCRIPCION',
             'GF',
             'GRUPO_FUN_DESCRIPCION',
             'FN',
             'FUNCIONL_DESCRIPCION',
             'SF',
             'SUBFUNCIONL_DESCRIPCION',
             'RA',
             'REASIGNACION_DESCRIPCION',
             'AI',
             'ACTIVIDAD_INST_DESCRIPCION',
             'MOD',
             'MODALIDAD_DESCRIPCION',
             'PP',
             'PROGR_PRES_DESCRIPCION',
             'CONCEPTO',
             'CONCEPTO_DESCRIPCION',
             'TG',
             'TIPO_GASTO_DESCRIPCION',
             'FF',
             'FUENTE_FINAN_DESCRIPCION',
             'EF',
             'ENTIDAD_FED_DESCRIPCION',
             'CLAVE_CARTERA',
             'PEF_2016'],
 'row-count': 1000,
 'time': 0.121,
 'valid': True}
```
