### ISSUE TITLE
Absolute row limit maximum in Pipeline

### ISSUE THREAD

**Issue by ethanwhite** [frictionlessdata/goodtables-py#107]
To start, I just wanted to say that I think this is a really great package and something we're interested in integrating into some of our workflows.

I have a questions about `ROW_LIMIT_MAX` in `pipeline.Pipeline`. If I'm reading everything correctly this sets an absolute upper limit on the maximum number of rows that can be processed. I'm curious about the reasoning for an absolute upper limit as opposed to sticking with a default number of rows and letting the user override it. The reason I ask is that I'm interested in using the package to do QC on entire data files and this would seem to prevent me from doing that for any reasonably large datafile.

**Comment by roll** [comment]
# goodtables.next

There is no such thing.

**Comment by pwalsh** [comment]
Fixed in https://github.com/frictionlessdata/goodtables-py/tree/next 

`next` will be tested for several weeks now before we merge onto `master`.

**Comment by ethanwhite** [comment]
Thanks @pwalsh! Much appreciated.
