### ISSUE TITLE
Update schema if extra/unordered headers has happened

### ISSUE THREAD

**Issue by roll** [frictionlessdata/goodtables-py#117]
# Overview

Those checks should update `fields` list.

**Comment by roll** [comment]
WILL BE DONE as part of #116

**Comment by pwalsh** [comment]
@roll I don't understand this. Goodtables shouldn't change anything passed to it, at least not by default.

**Comment by roll** [comment]
@pwalsh 
I'll get back to it on review. Current goodtables has an ability to work with extra fields etc.

**Comment by pwalsh** [comment]
Extra fields is an important feature. Things will break if the new code doesn't support it like the current codebase.

**Comment by roll** [comment]
I've added this ability (also things about order of fields). That was reason of closing it) So it's part of https://github.com/frictionlessdata/goodtables-py/pull/118

**Comment by roll** [comment]
Now there are options for it:
```
inspector = Inspector(order_fields=True, infer_fields=True)
```
First - will order badly ordered fields, second - infer fields for extra columns.

**Comment by pwalsh** [comment]
Fixed in https://github.com/frictionlessdata/goodtables-py/tree/next 

`next` will be tested for several weeks now before we merge onto `master`.
