### ISSUE TITLE
Blank and duplicate header error question

### ISSUE THREAD

**Issue by roll** [frictionlessdata/goodtables-py#119]
# Overview

Consider headers:

```
'name1', '', ''
```

How many error here:
- 2 blank header errors OR
- 2 blank header errors + 1 duplicate header error

**Comment by pwalsh** [comment]
@roll what happens currently in goodtables for this scenario?

**Comment by roll** [comment]
@pwalsh 
Current goodtables does:
```
2 blank header errors + 2(?) duplicate header error
```
I suppose 2 duplicate headers instead of 1 is a bug. But still empty counts as duplicate. It was initially raised by @georgiana-b but next version acts as expected then.
