### ISSUE TITLE
Support full Batch functionality

### ISSUE THREAD

**Issue by roll** [frictionlessdata/goodtables-py#125]
See - https://github.com/frictionlessdata/goodtables-py/blob/master/goodtables/pipeline/batch.py

**Comment by roll** [comment]
@pwalsh 
Now you have a good knowledge of next API and codebase. So in you opinion what we're missing? Because I'm not sure we do.

**Comment by pwalsh** [comment]
@roll 

The original design supports [this as a source for batch processing](https://github.com/okfn/data-quality-uk-25k-spend/blob/master/data/sources.csv). and takes arguments to know which column to take as the data source, and which to take as the schema source.

This could be slightly abstracted as an array of objects, with a key for data and a key for schema.

**Comment by roll** [comment]
@pwalsh 
Sorry, I've missed it. I'll add a profile for it.

**Comment by pwalsh** [comment]
@roll 

post task hooks: 

I really added that in a generic way to meet a very particular use case. I agree with moving the hooks code from good tables completely. Still, we *have* to not break data quality CLI at least, which this was designed for. [Example](https://github.com/frictionlessdata/data-quality-cli/blob/master/data_quality/main.py#L50).

I think if we look at that again, there is just a different way to do the same type of things.

@georgiana-b any thoughts?

**Comment by pwalsh** [comment]
@roll 

sleep:

it is a killer if you can't force a sleep between runs. This was a crude way to work around API rate limiting, by enforcing a rest between requests. We need some way to support this.

**Comment by roll** [comment]
@pwalsh 
do we need a flag to force synchronous inspection?

**Comment by pwalsh** [comment]
I don't think so. 

We can open this as a distinct issue and ship after V1. 

I think the correct treatment would be for the asynchronous workers to have a lookup table to reference, where keys are domains, and values are seconds since last request. Then we could use a crude sleep value to enforce a wait before next request (I know, it gets real complicated when the processing is async), and later, even build in support for reading `robots.txt` to be good web citizens and respect the request limits that webmasters request from us as consumers.

@amercader any thoughts?

**Comment by roll** [comment]
PART of issue moved to https://github.com/frictionlessdata/goodtables-py/issues/140

**Comment by roll** [comment]
@pwalsh 
This format - https://github.com/okfn/data-quality-uk-25k-spend/blob/master/data/sources.csv - or similar looks more like special case for DQCLI. I think better to add general `tables` preset and convert special cases on client level - https://github.com/okfn/data-quality-uk-25k-spend/blob/master/data/sources.csv

**Comment by pwalsh** [comment]
@roll ok! agreed.

**Comment by roll** [comment]
SPLIT:
- #140 
- #141
