### ISSUE TITLE
Click requirement conflict on a developer install

### ISSUE THREAD

**Issue by amercader** [frictionlessdata/goodtables-py#126]
Brand new virtualenv:

```
git clone git@github.com:frictionlessdata/goodtables-py.git
python setup.py develop
running develop
running egg_info

[...]

error: Installed distribution click 6.6 conflicts with requirement click>=3.3,<4.0a
```

goodtables requires `Click>=3.3`, jsontableschema requires `click>=3.3,<4.0a`.  So we either upper bound the requirement on goodtables or remove the upper bound on jsontableschema. Happy to submit a PR either way.

Also the requirement is pinned (`Click==3.3`) on `requirement/base.txt`, which in general is not in sync with setup.py.

**Comment by roll** [comment]
jts should be updated (I've missed that click version is outdated). I could fix and release in a few hours (when will get a laptop)

**Comment by amercader** [comment]
@roll thanks, no rush at all
