### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by roll** [frictionlessdata/goodtables-py#127]
# Description

We need to test all edge-cases etc. Many prev version data examples are in `data` folder.

# Tasks

- [ ] improve test coverage
- [x] set coverage threshold in coverals to 90%

**Comment by pwalsh** [comment]
@roll I;m fine with you closing this now, with the file additions you added.

**Comment by roll** [comment]
I prefer to improve test coverage before `final` release. Now it's just 83% and some edge-cases - https://github.com/frictionlessdata/goodtables-py/issues?q=is%3Aissue+is%3Aopen+label%3Abug - are not covered.

**Comment by roll** [comment]
MERGED #105

**Comment by roll** [comment]
DONE
