### ISSUE TITLE
Inspector method naming

### ISSUE THREAD

**Issue by roll** [frictionlessdata/goodtables-py#130]
# Overview

For now it's a `Inspector.inspect()`. @pwalsh suggest `inspector.run()`. Just something to decide. 

One thing we need without doubts - class-approach instead of just function `inspect()` (like `jsontableschema.validate()`). It's because class collect all settings and an instance of inspector could be used to inspect many datasets.

**Comment by pwalsh** [comment]
- `Collector.collect`
- `Extractor.extract`
- `Transformer.transform`
- `Loader.load`
- `Inspector.inspect`

vs.

- `Collector.run`
- `Extractor.run`
- `Transformer.run`
- `Loader.run`
- `Inspector.run`

For me, the answer is obvious, but I dont care too much. Whatever we merge now, we will stay with though.

Thoughts @amercader ?

**Comment by roll** [comment]
Problem with `run` could be making a class frozen. Consider in a future we need to add `validate` raising errors instead of returning a report or `iter_errors` from one table. If there is `run` already other names will be bad-looking.

**Comment by amercader** [comment]
So if I understand correctly @roll, your reservations in choosing `run` on all classes is that if we ever want to add a new method to the class API it won't look consistent, eg `Inspector.run()` + `Inspector.validate()` + `Inspector.iter_errors()`.

I always tend to favour explicitness so I'm leaning towards keeping the `inspect()` naming but I don't have a strong preference about it.

**Comment by roll** [comment]
@amercader 
I'm think so.

So let's go here with `inspect` for now. Also `tabulator` uses the same pattern for `parser.parse`, `loader.load` etc because I suppose it's more semantic.
