### ISSUE TITLE
Move spec.json source to data-quality-spec repo

### ISSUE THREAD

**Issue by roll** [frictionlessdata/goodtables-py#131]
# Description

I suppose we with @amercader need a few weeks to play with `spec.json` in the next codebase then we will be ready to make a PR to https://github.com/frictionlessdata/data-quality-spec

**Comment by pwalsh** [comment]
fine by me.

**Comment by roll** [comment]
GT.next requirements to spec:
- ordered
- errors have code, type, context

So I could make PR to spec repo with plain structure or preserve current 3 sections changing indexes to codes. GT could work with both.

**Comment by pwalsh** [comment]
@roll I'm completely happy to have this data structure in any form that you prefer.
