### ISSUE TITLE
[Docs] checklist of contraints implemented

### ISSUE THREAD

**Issue by patcon** [frictionlessdata/goodtables-py#135]
Sorry, just looking for confirmation that "unique" and "required" are not yet implemented in "next" branch. I am only asking because I saw tests in "master" that seemed to indicate they were at one point being validated :)

Might we be able to treat https://github.com/frictionlessdata/goodtables-py/issues/55 is an "epic" and add a little markdown checklist into the initial issue comment, laying out which constraints we're aiming to implement, and which are complete?

Thanks!

**Comment by roll** [comment]
@patcon 
I'll be pretty soon on it.

**Comment by roll** [comment]
I haven't tests it yet but current `goodtables.next` behavior should be - all constraints are supported but `error` will be `non-castable-value`.

**Comment by roll** [comment]
CLOSING IT IN FAVOR of https://github.com/frictionlessdata/goodtables-py/issues/55
