### ISSUE TITLE
Incorrectly parsed double quotes inside values

### ISSUE THREAD

**Issue by kravets-levko** [frictionlessdata/goodtables-py#142]
In CSV file values may contain double quotes inside of them. In this case, double quotes should be escaped: duplicated (`""`) or with some escape character, usually backslash (`\"`). GT does not support any of these cases and fails to parse such files:

``` csv
Test
"Test line 1"
"Test "" line 2"
"Test \" line 3"
```

**Comment by pwalsh** [comment]
hey @kravets-levko can you show an example file that GT fails on? This definitely should work for "most" cases, and I'd love to see what is breaking here.

**Comment by kravets-levko** [comment]
@pwalsh Sure
http://goodtables.okfnlabs.org/reports?data_url=https%3A%2F%2Fraw.githubusercontent.com%2Fkravets-levko%2Fdata%2Fmaster%2Fgt-fail-example.csv&format=csv&encoding=&schema_url=&ignore_empty_rows=y

**Comment by pwalsh** [comment]
@roll if this acts correctly in v1 I am happy to close this.

**Comment by roll** [comment]
@pwalsh 
I'll go thru all this issues tomorrow to check actuality.
