### ISSUE TITLE
ignore column order

### ISSUE THREAD

**Issue by hredestig** [frictionlessdata/goodtables-py#159]
Sorry if I'm just blind but can't find a way to ignore the order of the columns in my input table, is there a way to achieve that?

**Comment by roll** [comment]
You could use `order_fields` option or `--order-fields` CLI flag:
```
inspector = Inspector(..., order_fields=True)
```
It means schema fields will be re-ordered based on matches with column names.

**Comment by hredestig** [comment]
but of course, thanks!
