### ISSUE TITLE
Simple doc improvements to help the new user

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/goodtables-py#164]
* [ ] Couple of simple library examples at the top - the obvious stuff
  * [ ] Validate data in a datapackage (all or just one resource)
  * [ ] Validate data in a CSV with and without a JSON Table Schema
* [ ] Explain conceptually the two types of checking that the library does: Structure and Schema
* [ ] Give a CLI datapackage example
  * [ ] Explain what `infer-fields` does ...

**Comment by roll** [comment]
Thanks! MERGED #105 (all readme updates are consolidated to track here)
