### ISSUE TITLE
Make time measurement optional?

### ISSUE THREAD

**Issue by Fak3** [frictionlessdata/goodtables-py#169]
Right now reports include several 'time' fields with the time passed during inspection. In tests of `dpm` client I found this feature producing unstable results in the report output, and it is quite cumbersome to strip 'time' fields from all the table subreports down. 
It would be useful to be able to opt-out from this time measurements in the reports. For example add `timeit=False` kwarg to inspect() method.

**Comment by roll** [comment]
I'm not sure it's the right approach to work with a report. Report is a data container providing all information about given inspection. In the future it could be extended with additional keys (and it's not be marked as breaking changes). So it will not be a good practice to rely on it in the client code.

I suppose recommended way is process report first to be sure that it always will be containing only keys needed by the client to show it:
```python
report_to_show = whitelist_report_fields(report)
```

Also @Fak3 @rufuspollock FYI we've started to work on reusable components for rendering goodtables reports using modern javascripts frameworks. For it's not properly styled etc but we have a goal to provide this stuff:
- https://github.com/frictionlessdata/goodtables-react-js
- https://github.com/frictionlessdata/goodtables-vue-js

**Comment by roll** [comment]
WONTFIX
for now please re-open if further discussion is needed
