### ISSUE TITLE
Improve user-facing API

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/goodtables-py#186]
From @pwalsh:

1. MOVED to #198
2. MOVED to #198
3. CLI and Python interfaces: The new version of goodtables breaks consistency between the CLI and Python interfaces. `Inspector` is a new concept compared to old versions, and is the primary interface in Python. In CLI, inspector does not feature as a concept, and instead we expose the Inspector as `goodtables`. This is more in line with the old API semantics. However, on CLI, the order of arguments is reversed, and the user needs to provide the preset before the data. This is pretty confusing for no obvious reason.

---

From @rufuspollock:

Small suggestion for making this awesome library even better 😄 

Couple of convenience functions we could add:

```python=
# validate a data package
goodtables.validate_datapackage(url_or_path)

# validate an individual tabular data file 
goodtables.validate(datafile, schema=None)

datafile = url_or_path_to_table_data_or_fileobj_or_row_iterator # would be happy to just support fileobj and row iterator
schema = schema_url_path_or_file_obj_or_dict=None)
```

**Comment by pwalsh** [comment]
@danfowler would be interested in your feedback on these issues too

**Comment by roll** [comment]
> 3. CLI and Python interfaces: The new version of goodtables breaks consistency between the CLI and Python interfaces. Inspector is a new concept compared to old versions, and is the primary interface in Python. In CLI, inspector does not feature as a concept, and instead we expose the Inspector as goodtables. This is more in line with the old API semantics. However, on CLI, the order of arguments is reversed, and the user needs to provide the preset before the data. This is pretty confusing for no obvious reason.

Agree on this. I would say we need something like:
```
$ goodtables file.csv ...
$ goodtables datapackage.json --preset datapackage ...
```

**Comment by danfowler** [comment]
@pwalsh @roll  So I spent a bit of time reading through the README and playing the library just now, and here are some thoughts:

- Related issue to CLI/Inspector confusion re: more granular checks on the CLI: https://github.com/frictionlessdata/goodtables-py/issues/175
- Similarly, the use of `command` on the CLI and `preset` in the Inspector is confusing.  I can understand why `command` is used in that context, and I also get that they don't map one to one. 
 I would agree that something like `goodtables datapackage.json --preset datapackage` may be better, but it still seems like even `preset` could be replaced by something like `source` conceptually.  
- It does seem like referring to a Data Package by its directory as well as its descriptor would be nice (`goodtables datapackage datapackage.json` seems quite redundant 😄 ), maybe e.g `goodtables . --preset datapackage` inside a Data Package directory?
- For `Inspector()`, we can refer to the checks we want to run by their code string for the `checks` keyword argument, but for the `custom_checks` keyword argument, we refer to these checks by their function, so it's a bit uneven there:

    `inspector = Inspector(checks={'flatline-check': True}, custom_checks=[flatline_check])`
- I think the README could do with a spellcheck and formatting pass, which I would be happy to do

**Comment by roll** [comment]
@danfowler 
Thanks, Dan. Great input. I've consolidated here your granular checks issue.

**Comment by pwalsh** [comment]
I'm not sure about merging the enhancements from @rufuspollock here. Those suggestions are great but are very much about convenience, whereas the other issues here are about distinct inconsistencies or undocumented features.

WDYT @roll ?

**Comment by roll** [comment]
@pwalsh 
I more prefer if we go thru all API improving ideas in one run before v1 release. So having it in one issue could help to get feedback from more people.
