### ISSUE TITLE
Indicate in report what's checks have been done for every table?

### ISSUE THREAD

**Issue by roll** [frictionlessdata/goodtables-py#205]
# Overview

We could add `report.tables[].checks (str[])` property to provide explicit feedback what's checks have been done. Otherwise sometimes a report could be confusing because e.g. without provided `schema` or `infer_schema=True` all schema checks will be just ignored without an indication.

**Comment by pwalsh** [comment]
@roll yes.

**Comment by roll** [comment]
MERGED into https://github.com/frictionlessdata/goodtables-py/issues/341
