### ISSUE TITLE
Implement new advanced check

### ISSUE THREAD

**Issue by roll** [frictionlessdata/goodtables-py#207]
# Overview

Recently we've started `goodtables.contrib` module to simplify `goodtables` extension process. Here is a documentation for already implemented advanced checks - https://github.com/frictionlessdata/goodtables-py#validation-against-advanced-checks. 

But there is still a lot of potential checks to implement. This meta issue will help to contribute on it. Writing new checks for `goodtables` is extremely simple.

# Ideas

- integer ranges (#214)

# Plan

- let's discuss in comment proposed checks first
- select name for new check like `possible-noise-text`
- copy https://github.com/frictionlessdata/goodtables-py/blob/master/goodtables/contrib/checks/blacklisted_value.py to new check module
- add new check module to configuration - https://github.com/frictionlessdata/goodtables-py/blob/master/goodtables/config.py
- write an actual code for new check
- write tests and readme for new check

**Comment by ppKrauss** [comment]
Hi, perfect, thanks @roll.  

-----

A final comment: the "all reasonable *integer ranges* representations at CSV" are only one example of the diversity that emerges from "full free"...  
I dislike full-free in *data interchange*, and is impossible to obtain  a interoperable ecosystem with it... I preffer [convention over configuration](https://en.wikipedia.org/wiki/Convention_over_configuration)... So, translating principles into good practices: it is better to standardizate before to offer a full-free self-service of datatype variants. Perhaps using recommendations (not obligations) and good examples... A **"goodTables Handbook for complex datatypes"**.
