### ISSUE TITLE
Error at CSV with no changes

### ISSUE THREAD

**Issue by ppKrauss** [frictionlessdata/goodtables-py#213]
At https://goodtables.io/github/datasets-br/state-codes

The changed file is the valid one (`br-state-codes.csv`), the strange error (no clues?) is about a `ref-applications.csv` that have no changes.

PS: the [blame at datapackage.json](https://github.com/datasets-br/state-codes/blame/master/datapackage.json) shows only valid change at line 200.

**Comment by roll** [comment]
@ppKrauss 
Here is a `goodtables-py` output:

```python
python -m goodtables.cli https://raw.githubusercontent.com/datasets-br/state-codes/master/datapackage.json
/home/roll/projects/goodtables-py/.python/lib/python3.5/site-packages/datapackage/package.py:78: UserWarning: Resource property "url: <url>" is deprecated. Please use "path: [url]" instead (as array).
  UserWarning)
DATASET
=======
{'error-count': 15,
 'preset': 'datapackage',
 'table-count': 2,
 'time': 6.873,
 'valid': False}
---------
Warning: Data Package "https://raw.githubusercontent.com/datasets-br/state-codes/master/datapackage.json" has a validation error "'title' is a required property"
Warning: Data Package "https://raw.githubusercontent.com/datasets-br/state-codes/master/datapackage.json" has a validation error "'title' is a required property"
Warning: Data Package "https://raw.githubusercontent.com/datasets-br/state-codes/master/datapackage.json" has a validation error "'title' is a required property"
Warning: Data Package "https://raw.githubusercontent.com/datasets-br/state-codes/master/datapackage.json" has a validation error "'title' is a required property"

TABLE [1]
=========
{'datapackage': 'https://raw.githubusercontent.com/datasets-br/state-codes/master/datapackage.json',
 'encoding': None,
 'error-count': 0,
 'format': 'inline',
 'headers': ['report',
             'name',
             'url',
             'adherence',
             'usedColumns',
             'description'],
 'row-count': 3,
 'schema': 'table-schema',
 'scheme': None,
 'source': 'https://raw.githubusercontent.com/datasets-br/state-codes/master/data/ref-applications.csv',
 'time': 0.811,
 'valid': True}

TABLE [2]
=========
{'datapackage': 'https://raw.githubusercontent.com/datasets-br/state-codes/master/datapackage.json',
 'encoding': None,
 'error-count': 15,
 'format': 'inline',
 'headers': ['subdivision',
             'name_prefix',
             'name',
             'id',
             'idIBGE',
             'place_id',
             'wdId',
             'lexLabel',
             'creation',
             'extinction',
             'category',
             'timeZone',
             'utcOffset',
             'utcOffset-DST',
             'postalCode_ranges',
             'notes'],
 'row-count': 34,
 'schema': 'table-schema',
 'scheme': None,
 'source': 'https://raw.githubusercontent.com/datasets-br/state-codes/master/data/br-state-codes.csv',
 'time': 6.359,
 'valid': False}
---------
[-,2] [non-matching-header] Header in column 2 doesn't match field name "name" in the schema
[-,3] [non-matching-header] Header in column 3 doesn't match field name "id" in the schema
[-,4] [non-matching-header] Header in column 4 doesn't match field name "idIBGE" in the schema
[-,5] [non-matching-header] Header in column 5 doesn't match field name "place_id" in the schema
[-,6] [non-matching-header] Header in column 6 doesn't match field name "wdId" in the schema
[-,7] [non-matching-header] Header in column 7 doesn't match field name "lexLabel" in the schema
[-,8] [non-matching-header] Header in column 8 doesn't match field name "creation" in the schema
[-,9] [non-matching-header] Header in column 9 doesn't match field name "extinction" in the schema
[-,10] [non-matching-header] Header in column 10 doesn't match field name "category" in the schema
[-,11] [non-matching-header] Header in column 11 doesn't match field name "timeZone" in the schema
[-,12] [non-matching-header] Header in column 12 doesn't match field name "utcOffset" in the schema
[-,13] [non-matching-header] Header in column 13 doesn't match field name "utcOffset-DST" in the schema
[-,14] [non-matching-header] Header in column 14 doesn't match field name "postalCode_range" in the schema
[-,15] [non-matching-header] Header in column 15 doesn't match field name "notes" in the schema
[-,16] [extra-header] There is an extra header in column 16
```

It seems there is a `name_prefix` headers that doesn't match the schema.

**Comment by ppKrauss** [comment]
Hi, the error  *"'title' is a required property"* say nothing without line number or block indication, about where I need to add the *title* property.

**Comment by roll** [comment]
@ppKrauss 
I totally agree that's this error message is useless. I've created an issue for it - https://github.com/frictionlessdata/datapackage-py/issues/169

Your data package is no valid because `descriptor.sources[]` requires `title` - https://raw.githubusercontent.com/datasets-br/state-codes/master/datapackage.json

**Comment by ppKrauss** [comment]
Hi, thanks @roll , the error perhaps changed after add title, but I not understand: https://goodtables.io/github/datasets-br/state-codes/jobs/29

-----

Other suggestion. Now that we have "global v1.0", the error messages can also link to the stable standard  (the https://specs.frictionlessdata.io/data-package/#sources  in this case).

**Comment by roll** [comment]
@ppKrauss 
I think that's the same error I've mentioned in https://github.com/frictionlessdata/goodtables-py/issues/213#issuecomment-328480631:

In the https://raw.githubusercontent.com/datasets-br/state-codes/master/datapackage.json resource fields:
- name
- id
- subdivision

But in the https://raw.githubusercontent.com/datasets-br/state-codes/master/data/br-state-codes.csv:
- subdivision
- name
- **prefix_name**
- if

**Comment by roll** [comment]
It's a bug that's you've got `extra-header` error instead of `non-matching-header` error. It's already fixed in `goodtables-py`. So it will be applied to `goodtables.io` soon - https://github.com/frictionlessdata/goodtables.io/issues/263

**Comment by ppKrauss** [comment]
The `name_prefix` was good as showed by https://goodtables.io/github/datasets-br/state-codes/jobs/27 ... and never changed, so it is not the real error.

Understanding that was a Goodtables-bug that I must wait (to be corrected online)... Thanks the reply, ok, I will wait.

**Comment by roll** [comment]
@ppKrauss 
> The name_prefix was good as showed by https://goodtables.io/github/datasets-br/state-codes/jobs/27 ... and never changed, so it is not the real error.
I can't agree on it :smiley: 

Take a look on a job history:
![states](https://user-images.githubusercontent.com/557395/30335716-c1e8de00-97eb-11e7-8370-80503c034e3b.png)

Starting from this commit - https://github.com/datasets-br/state-codes/commit/cd1e580374418a1de4fa616aabd8b778a6877f87 - jobs started to fail. 

On this commit two column have been added to data - `name_prefix` and `postalCode_ranges`. But only one field has been added to fields - `postalCode_ranges`. 

So for now the data package is invalid because schema fields doesn't match data headers (`extra-headers`) error.

**Comment by ppKrauss** [comment]
Oops, sorry @roll, thanks all the observations. Now is working fine!

https://goodtables.io/github/datasets-br/state-codes/jobs/30

**Comment by roll** [comment]
You're welcome.
