### ISSUE TITLE
Integer ranges, it is possible?

### ISSUE THREAD

**Issue by ppKrauss** [frictionlessdata/goodtables-py#214]
It is possible to express integer ranges as in [SQL Range Types](https://www.postgresql.org/docs/current/static/rangetypes.html)?

**Comment by roll** [comment]
@ppKrauss 
Could you please add a little bit more context? But if you've got you right `maximum/minimum` constraints of the Table Schema spec are exactly want you need - http://specs.frictionlessdata.io/table-schema/#constraints

**Comment by ppKrauss** [comment]
Simplest: integer intervals, "from 1 to 9" is `[1 9]`.

Codes with integer suffixes:  "from A1 to A9" is `[A1 A9]`.

ISO dates:  "from 2016-05-22  to 2017-06-09" is `[2016-05-22 2017-06-09]`.

Integer intervals in array:  "from 1 to 9 and from 13 to 16" is `[1 9] [13 16]`.

Of course, need an standard syntax (exist?) that can be also `"[1,9],[13,16]"`, `[1 9;13 16]` or etc.

----

There are so many applications as SQL use cases... I have only this one with a `datapackage.json`: see column *postalCode_ranges* at https://github.com/datasets-br/state-codes/blob/master/data/br-state-codes.csv

**Comment by roll** [comment]
@ppKrauss 
No. There is no such thing for now. 

May be partially it could be achieved using `contrib.checks` - https://github.com/frictionlessdata/goodtables-py#validation-against-advanced-checks. Or implementing a new one - https://github.com/frictionlessdata/goodtables-py/issues/207

But for some standard syntax on data package level it's better to create an issue for specs - https://github.com/frictionlessdata/specs/issues

**Comment by roll** [comment]
MOVED
https://github.com/frictionlessdata/goodtables-py/issues/207
