### ISSUE TITLE
Got "TypeError: must be str, not list" when set infer_schema=True

### ISSUE THREAD

**Issue by smeeklai** [frictionlessdata/goodtables-py#217]
I'm not sure whether it's a bug or I did it incorrectly.

I created schema.json which consists of 7 primary columns in field descriptor to check against a CSV file with 38 columns. However, I got the above error when I set `infer_schema=True`. I already used `validate()` to confirm that my descriptor is correct.

I also did a little more tests and found its malfunctional behaviors of this parameter. There was no problem when I tested with CSV files which have less columns. It also work correctly with the original CSV file if I don't set `infer_schema=True`. Looks like the problem occurs when a CSV file has too many columns.

CSV headers:
`['story', 'code 1', 'code 1.1', 'code 1.2', 'code 1.3', 'code 1.4', 'code 1.5', 'code 2', 'code 2.1', 'code 2.2', 'code 2.3', 'code 2.4', 'code 2.5', 'code 3', 'code 3.1', 'code 3.2', 'code 3.3', 'code 3.4', 'code 3.5', 'code 4', 'code 4.1', 'code 4.2', 'code 4.3', 'code 4.4', 'code 4.5', 'code 5', 'code 5.1', 'code 5.2', 'code 5.3', 'code 5.4', 'code 5.5', 'context', 'brs id', 'question', 'project name', 'project detail', 'year', 'no']`

schema.json:
```
{
    "fields": [
        {
            "name": "story",
            "type": "string",
            "format": "default" 
        },
        {
            "name": "context",
            "type": "number",
            "format": "default",
            "constraints": {
                "minimum": 0,
                "maximum": 3
            }
        },
        {
            "name": "brs id",
            "type": "number",
            "format": "default",
            "constraints": {
                "required": true
            }
        },
        {
            "name": "question",
            "type": "number",
            "format": "default",
            "constraints": {
                "required": true
            }
        },
        {
            "name": "project name",
            "type": "string",
            "format": "default",
            "constraints": {
                "required": true
            }
        },
        {
            "name": "project detail",
            "type": "string",
            "format": "default",
            "constraints": {
                "required": true
            }
        },
        {
            "name": "year",
            "type": "year",
            "format": "default",
            "constraints": {
                "required": true
            }
        }
    ],
    "missingValues": [
        "",
        "NaN",
        "-",
        " "
    ]
}
```

Error:

> TypeError Traceback (most recent call last)
> <ipython-input-92-56c4117b48bc> in <module>()
> ----> 1 val = validate('test.csv', headers=1, schema='schema.json', order_fields=True, infer_fields=True)
> 
> /Users/satjapongmeeklai/anaconda3/lib/python3.6/site-packages/goodtables/validate.py in validate(source, **options)
>      45     # Validate
>      46     inspector = Inspector(**settings)
> ---> 47     report = inspector.inspect(source, preset=preset, **options)
>      48
>      49     return report
> 
> /Users/satjapongmeeklai/anaconda3/lib/python3.6/site-packages/goodtables/inspector.py in inspect(self, source, preset, **options)
>      78                 tasks.append(pool.apply_async(self.__inspect_table, (table,)))
>      79             for task in tasks:
> ---> 80                 table_warnings, table_report = task.get()
>      81                 warnings.extend(table_warnings)
>      82                 table_reports.append(table_report)
> 
> /Users/satjapongmeeklai/anaconda3/lib/python3.6/multiprocessing/pool.py in get(self, timeout)
>     606             return self._value
>     607         else:
> --> 608             raise self._value
>     609
>     610     def _set(self, i, obj):
> 
> /Users/satjapongmeeklai/anaconda3/lib/python3.6/multiprocessing/pool.py in worker(inqueue, outqueue, initializer, initargs, maxtasks, wrap_exception)
>     117         job, i, func, args, kwds = task
>     118         try:
> --> 119             result = (True, func(*args, **kwds))
>     120         except Exception as e:
>     121             if wrap_exception:
> 
> /Users/satjapongmeeklai/anaconda3/lib/python3.6/site-packages/goodtables/inspector.py in __inspect_table(self, table)
>     178                         break
>     179                     check_func = getattr(check['func'], 'check_headers', check['func'])
> --> 180                     check_func(errors, cells, sample)
>     181                 for error in errors:
>     182                     error['row'] = None
> 
> /Users/satjapongmeeklai/anaconda3/lib/python3.6/site-packages/goodtables/checks/extra_header.py in check_headers(self, errors, cells, sample)
>      36                     column_sample.append(value)
>      37                 schema = Schema()
> ---> 38                 schema.infer(column_sample, headers=[cell['header']])
>      39                 cell['field'] = schema.fields[0]
>      40
> 
> /Users/satjapongmeeklai/anaconda3/lib/python3.6/site-packages/tableschema/schema.py in infer(self, rows, headers)
>     187                 diff = headers_length - row_length
>     188                 fill = [''] * diff
> --> 189                 row = row + fill
>     190             # build a column-wise lookup of type matches
>     191             for index, value in enumerate(row):
> 
> TypeError: must be str, not list

**Comment by roll** [comment]
@smeeklai 
Thanks for the detailed bug report. I'll fix it.

**Comment by roll** [comment]
@smeeklai 
Quick thought - have you tried `infer_fields=True` instead of `infer_schema=True`?

**Comment by roll** [comment]
I've checked - I think it's a problem because `infer_schema=True` (infer brand-new schema) is used instead of `infer_fields=True` (infer only missing fields).

But I'd like to see a data file example to fix this still incorrect behavior for `infer_schema` - it still should not raise an error I suppose. But have to check a data file sample.

**Comment by smeeklai** [comment]
@roll oh, you got it right. I mistyped the parameter name. I actually meant `infer_fields=True`
