### ISSUE TITLE
Allow glob paths in the CLI

### ISSUE THREAD

**Issue by vitorbaptista** [frictionlessdata/goodtables-py#229]
# Overview

We'd like to pass multiple paths to `goodtables` CLI command (consider `goodtables data/*.csv`).

# Plan

- [ ] implement multiple `path` argument in `cli.py` using `nested` preset for `validate` function: `validate([{'source': 'path1'}, {'source': 'path2'}, ...], preset=nested)`
- [ ] implement tests and update readme

---

_From @vitorbaptista_

My use-case is that I have a folder `./data` with many different CSVs. I'd like to call `goodtables data` or `goodtables data/*.csv` and have it automatically run goodtables for all files.

**Comment by roll** [comment]
@vitorbaptista 
I agree. I've added a spec.

**Comment by vitorbaptista** [comment]
Fixed on https://github.com/frictionlessdata/goodtables-py/pull/241
