### ISSUE TITLE
Implement limits disabling

### ISSUE THREAD

**Issue by vitorbaptista** [frictionlessdata/goodtables-py#230]
# Overview

We'd like to have ability to disable table/row/error limits instead of setting very big number to it. Also current default limits seem very small.

# Plan

- [ ] increase default limits in `config.py`
- [ ] share selected implementation in this thread
- [ ] implement option 1
  - [ ] implement `disable_limits=False` argument for `validate.py:validate` function
  - [ ] implement `--disable-limits` flag for CLI in `cli.py`
- [ ] OR implement option 2
  - [ ] support `row/table/error_limit=False` argument value for `validate.py:validate` function
  - [ ] implement `--no-row/table/error-limit` flag for CLI in `cli.py`
- [ ] implement tests and update readme

---

_From @vitorbaptista_

I don't know if it's possible currently, but something like `goodtables --row-limit 0 data.csv` would avoid me having to do have to set a high row limit when in fact I want to disable it.

**Comment by roll** [comment]
@vitorbaptista 
No. It's not possible for now. I've added a spec for this feature. Because there are 3 limits: table, error, row; I think the best way is to implement `disable_limits` argument/flag for all of them.

**Comment by vitorbaptista** [comment]
In general, I think it's better UX to keep the flags self-contained. What I mean is that if I want to change the value of `row-limit`, I should change it directly, and not via separate configuration option. This keeps the interdependency between configuration options low (ideally, they're all independent), and avoids potential dubious behaviors like `goodtables --row-limit 100 --disable-limits=row data.csv`. This example is obvious, because it's on the same call, but you can imagine it being more subtle when one of the options is defined somewhere else (e.g. `goodtables.yml`).

I think the best would be either `--row-limit off`, or magic values like `--row-limit 0`. As a plus, this should also be easier to implement.

WDYT?

**Comment by roll** [comment]
@vitorbaptista 
I've added second implementation path to the spec. My initial guess was that if user wants to disable some limits he probably looks for fully unlimited usage. So one option could be more handy. Don't have preferences between 1/2.

Also I think `click` supports flags like `--no-row-limit`. We could use it. WDYT?

**Comment by vitorbaptista** [comment]
Fixed on https://github.com/frictionlessdata/goodtables-py/pull/241, we allow `--errorr-limit -1` to disable it.
