### ISSUE TITLE
Add support for foreign keys?

### ISSUE THREAD

**Issue by kishoreabhishek** [frictionlessdata/goodtables-py#238]
Below is my datapackage.json

`{ "name": "testing", "resources": [ { "name": "data", "path": "data.csv", "schema": { "fields": [ { "name": "id", "type": "string", "constraints": { "required": true } }, { "name": "name", "type": "string" }, { "name": "description", "type": "string" }, { "name": "amount", "type": "number" } ], "primaryKey": ["id"] } }, { "name": "data2", "path": "data2.csv", "schema": { "fields": [ { "name": "id" }, { "type": "string", "name": "comment" } ], "foreignKeys": [ { "fields": ["id"], "reference": { "resource": "data", "fields": ["id"] } } ] } } ] }`

**data.csv**
id,name,description,amount
A999,Taxes,Taxes we collect,10000.5
A5032,Parking Fees,Parking fees we collect,2000.5

**data2.csv**

id,comment
A3001,comment1
A3001,comment2
A5032,comment3

As you can see data2.csv has A3001 in id column but data.csv does not but when I validate
report = validate('datapackage.json',preset='datapackage')

The report does not show any error

Can foreign key constraint check be added to goodtables-py.

**Comment by roll** [comment]
@kishoreabhishek 
Thanks. As said in the initial issue - foreign keys is not a part of Data Quality Spec for now. So probably we could implement it as a an advanced check - https://github.com/frictionlessdata/goodtables-py/issues/207

**Comment by steko** [comment]
Hello, just quickly checking if this is indeed planned as an advanced check in goodtables?

**Comment by roll** [comment]
@steko 
There are no plans to implement it at the moment by the core team. But it's open for implementation as an outside contribution. It shouldn't be hard to achieve.
