### ISSUE TITLE
Problem with geopoint as an object validation

### ISSUE THREAD

**Issue by roll** [frictionlessdata/goodtables-py#244]
# Overview

Datapackage - https://raw.githubusercontent.com/Stephen-Gates/example-data-packages/b7b1c72aed0939d25073db083dc6b167e7338245/geo-location-fk/datapackage.json

It should be fixed on `tableschema` level:
```
valid = cell['field'].test_value(cell['value'], constraints=['required'])
```
This call fails because cast `geopoint` is a tuple but expected format is a object. 

I suppose `field.test_value` should not use `field.cast_value` for `required` check.

**Comment by vitorbaptista** [comment]
@roll I can't reproduce this error, and I'm not sure what was it in the first place. Running `goodtables https://raw.githubusercontent.com/Stephen-Gates/example-data-packages/b7b1c72aed0939d25073db083dc6b167e7338245/geo-location-fk/datapackage.json` is successful. Maybe fixed by some other change?

**Comment by roll** [comment]
@vitorbaptista 
I can't reproduce it either. 

CLOSED
