### ISSUE TITLE
Add folder for virtual environment

### ISSUE THREAD

**Issue by dahlbaek** [frictionlessdata/goodtables-py#245]
In the **Contributing** section of the `README.md`, it is recommended that one use a virtual environment. But it is not clear where to install this virtual environment. In the [datapackage-py](https://github.com/frictionlessdata/datapackage-py) repository, the situation is handled with the lines
```
# Virtualenv
venv/
```
in `.gitignore`. Perhaps a similar solution would be beneficial here?

If you would like, I can create a PR with the addition to `.gitignore` and a corresponding update to `README.md`.

**Comment by vitorbaptista** [comment]
@dahlbaek Sorry for the delay in answering this, and thanks for the report. There's a bit of an inconsistency, we used to use `venv/` as virtual env, but changed to simply `env/`. That's what we have in our `.gitignore`, but some other repositories also ignore `venv`.

As virtualenv is a pretty common tool in Python, I don't think there's a need to explain how to use it on our README, so I'm closing this as a `wontfix`.

Please keep opening issues if you find anything that could be improved.
