### ISSUE TITLE
[epic] Error creation API improvements discussion

### ISSUE THREAD

**Issue by roll** [frictionlessdata/goodtables-py#246]
This is a discussion of possible improvements of the error creation API of the checks protocol.

## Current state

For now to add an error being inside a check you should append an `error` dict to the `errors` list (available for the check). Here an example:

```python
@check('blank-header', type='structure', context='head')
def blank_header(errors, cells, sample=None):
    
    # ...
    
    # Add error
    message = spec['errors']['blank-header']['message']
    message = message.format(column_number=cell['number'])
      errors.append({
        'code': 'blank-header',
        'message': message,
        'row-number': None,
        'column-number': cell['number'],
    })
```

The whole API is based on 2 standards:
- Data Quality Spec (`goodtables.spec` is public API)
- goodtables report structure (created `error` dict follows it)

So it's a part of core goodtables design that creating an error is not relying on any programming API but only on open standards (DQS, GT-report) using explicit raw data structure. It allows almost infinite flexibility because any check could create any error compliant with the GT report. Even if for now we don't know what kind of checks we/users will be creating in the future.

## Possible improvements 

I don't see major design problems with current solution. It withstood the test of time and addition of any kind of custom checks. I think because it's highly decoupled from other parts for the goodtables and relying only on open standards.

Theoretically, the way how a user adds/creates an error could be improved with some helper. But it's a thin ice here as it was described in the previous section - it should not create dependencies between different concepts and create a regression to overall design in other ways.

## Proposal 1

There is a proposal to add errors like this:

```python
error = Error(
  'pattern-constraint',
  cell, 
  message_substitutions=message_substitutions
)
errors.append(error)

error = Error(
  'blacklisted-value', 
  row_number=cells[0]['row-number'], 
  message=message
)
errors.append(error)
```

If I get it right there is an `Error` class that works like a helper to create an error. It could take or could not take `cell` dict (based on availability).

This proposal creates a dependency between `error` and `cell` and also **it's breaking**. It makes creating an error a little bit more convenient but hides open standards under the custom API. So you should learn not only Data Quality Spec, Goodtables Report but also Error API. 

Some thoughts aside. I think the software industry has a tendency to prefer short-time convenience over proper design. Because of this, we're having you know all these programs with hundreds of functions and classed calling each other etc. It simplifies life on some point of time but on next point in time, it makes it cognitively not accessible and not scalable because of nesting, implicitness etc. I think everyone been in the situation when you're trying to understand some code but jumping from one file to another just finding the place where the real action is happening. Books say duplication is your first enemy, always create additional functions etc. But I think in engineering there are much more important principles to follow like encapsulation, proper (and minimal) dependency structure etc

## Proposal 2

So I think we still could use an idea of introducing error creating helpers without regression for goodtables design and **without breaking changes**.

We could do something like:

```python
# Using helper
register_error(errors,
  code='duplicate-row',
  row_number=1,
  column_number=2,
  message=message,
  # message_substitutions?
  ...
)

# Customizing errors list class
errors.add(
  code='duplicate-row',
  row_number=1,
  column_number=2,
  message=message,
  ...
)
```

It will allow not using `goodtables.spec` inside standard checks. But this solution also clearly use implicit approach over explicit approach.

## Conclusion

For now, I don't see valid reasons to change error creation API. Analysed proposals provide some convenience but I don't think it's game changers so it makes sense to introduce a regression to overall goodtables design. 

I think even if it's not clear for now - like in 2 years after dozens of new checks will be added and a brand-new type of checks will be introduced (not only head/body/etc) it becomes much clearer why the current fully decoupled design has been selected.

**Comment by roll** [comment]
@brew 
@vitorbaptista 
@amercader 
@akariv 
@pwalsh 
Goodtables update discussion.

**Comment by pwalsh** [comment]
@roll this issue is redundant - the [PR](https://github.com/frictionlessdata/goodtables-py/pull/240) has been open since December, and opening this extremely detailed epic is to me is completely the wrong approach, wasting time and energy.

I'm supportive of the changes made by @vitorbaptista on technical grounds from a high-level assessment, and in generally supporting his role as Engineering Lead at OKI.

Please address specific technical issues in the PR, and work towards what needs to be done to merge the changes. I recommend closing this issue.

**Comment by vitorbaptista** [comment]
@roll I think you're mixing different things here.

* The internal implementation isn't tied to the Data Quality Spec
  Depending on the language, we can implement using classes, functions, or any other structure. What matters is that the output report follow the spec, not the implementation.

* Time doesn't test software, change does
  Correct me if I'm wrong, but it seems not many people are using `goodtables-py`. I haven't seen any custom checks built by others, with most usage coming from you and Adrià developing goodtables.io.

> So you should learn not only Data Quality Spec, Goodtables Report but also Error API.

I don't think people need to know about the Data Quality Spec, only the Error and other goodtables APIs. The only exception I can see is if they want to overwrite a check.

> This proposal creates a dependency between `error` and `cell`

The dependency already exists. An error can be relative to a specific cell even with the current code. My PR just makes it explicit by passing the `cell` itself, instead of only the `row-number` and `column-number`.

> Books say duplication is your first enemy, always create additional functions etc. But I think in engineering there are much more important principles to follow like encapsulation, proper (and minimal) dependency structure etc

The intent of the Error (and cell) changes was to reduce code duplication by encapsulating the logic on how to create an error in a single place (the Error class). This is especially important here because we allow people to write custom checks. As it is now, these checks need to create the Error dict manually, which means that the knowledge of what an Error contains is spread not only across `goodtables-py`, but also any custom check.

**Comment by roll** [comment]
@vitorbaptista 
Your words totally make sense. And in almost in every case it's a great strategy to hide internal state of the objects. Even more, it's only one correct way for most of the cases.

I just want to share the high-level vision of the whole FD projects with you so you will be able to understand the reasons why this protocol has end-up like this. I think it's obvious that both of your proposals were considered by me at some early stages of the `goodtables`. Because I worked a lot of time on it and had an ability to iterate on it a lot.

The whole FD project is based on the specifications for structured data. I mean the Frictionless Data specs family. For now, it's Data Package/Table Schema. But going forward I almost sure Data Quality Spec and even probably goodtables report in some form will join the family (e.g. see - https://github.com/frictionlessdata/implementations/issues/30)

If you take a look at the `tableschema/datapackage` - it's a core part of the design that user should know the Frictionless Data specifications. It's only wrappers around these specs. If you take a step back and looks at the goodtables.io family - that's not about `goodtables-py` or something. It's a **wrapper** around Data Quality Spec. All this software are just a wrapper around this spec. So this specs knowledge is a core of the whole eco-system.

Let's now take a look at APIs that FD stack proposes. There are two kinds:
- user-oriented API like:
  -  `dp = new Datapackage('will work with any kind of input`) 
  - or `goodtables.validate('automagically work with tables/package/etc)`
  - etc
- low-level APIs mostly for OKI internal use and a very skilled outside contributors:
  - `tabulator.Loader/Parser/Writer`
  - `tableschema.Storage`
  - `goodtables.preset/check`

There is a conceptual difference between these two categories - the first group is optimized for best user experience, the second group is about flexibility and scalability. In high-level you don't really care how nice `tabulator.Parser` API if that's not blocking you from adding new data sources.

The same with `goodtables` iteration protocol - it's on purpose and by design **fully open protocol**. You give all your keys to the check writers because on this level of the stack you need full flexibility and this API not for the masses like an API to open data package.

Don't forget that errors and cells are also a communication protocol allowing checks on different levels to communicate. And I'm pretty sure in the future there will be more check context extending current `head/body/etc` with some state-full context etc 

For example, consider this data quality check requirements:
- on every row collect a tabular problem X and create an error for it
- on table level extract all these problems, remove some errors based on business rule
- put some errors back to the errors list with updated messages and some custom error fields
- create new threshold error with some summary and add it to the list

And based on millions of use cases for the tabular data validation - it's not kind of fantastic use case.  A check like this is fully expected check at some point of the `goodtables` lifetime. And a lot of other very complex checks.

So again I really understand what you're proposing - it's a natural and good instinct to do things like this with almost any APIs. But exactly in this situation, it means starting **to close this open protocol**. If you will decide to go this way now - my prediction is that in a year or half you will be pushed by new checks requirements to revert these changes or start to use a lot of hacks to overcome newly introduced limitations. 

There is no silver bullet in software development. It's hard to find a better enemy of exposing the internal state to the user than me. But requirements of this exact software and my experience has convinced me to be flexible here.
