### ISSUE TITLE
[epic] Cell iteration API improvements discussion

### ISSUE THREAD

**Issue by roll** [frictionlessdata/goodtables-py#247]
This is a discussion of possible improvements of the cell iteration API of the checks protocol.

## Current state

The cell iteration API is probably the most complex part of goodtables because it has to deal with many moving parts of the real world data and standards:
- missing headers/values
- irregular number of columns
- changing/inferring fields 
- ordering fields by client request
- changing/casting values using Table Schema
- etc (we could put here the whole Data Quality Spec)

The same as with Error creation API the base object here is a dict - `cell` dict:

```python
cell['header']
cell['field'] # tableschema.Field instance
cell['value']
cell['column-number'] # for now it's 'number' because initially `cell` has name `column`. Probably we need to rename it to `column-number' in non-breaking manner
```

Here is used dict because it can't be class (performance reasons) and it can't be tuple/namedtuple (checks should be able to mutate the cell).

Because of data/schema inconcictency:

```python
cell['column-number'] # guaranteed to exist
# ---
cell['header'] # could be missing
cell['field'] # could be missing
cell['value'] #could be missing
```

Because we also need to handle empty/null/etc values existence should be checked like this:

```python
# correct
if 'value' in cell

# WRONG
if cell.get('value') # could be just null/empty value
```

The main concept here that checks is decoupled with actual cell keys existence. Different checks require a different amount of present keys e.g.:

```python
@check('duplicate-header', type='structure', context='head')
def duplicate_header(errors, cells, sample=None):
    for cell in cells:
        if 'header' in cell:
            # perform check
```

So in this case, `duplicate-headers` check to perform require an existence of `cell['header']`. Otherwise, cell is just skipped.

Some checks could ensure something like this:

```python
if 'header' in cell and 'field' in cell:
   # perform check
```            

Or other combinations including ensuring that there are all 4 keys are available.

This approach allows us to make checks highly flexible and scalable. Even if for now we don't know what kind of checks will be writing in the future we have decoupled design to guarantee that there will not be edge case which can't be covered.

As said a check could mutate the `cell` dict. For example:
- set `cell['field']` after inferring the field
- update `cell['value']` after casting the value
- etc

Also, check could remove any `cell` from the `cells` list. It means that the removed cell will not be checked in next checks. Like `cell is already marked invalid - removing it`

On the design stage, there was a lot of other ideas how to mark cell is invalid to prevent next checks but all of them has failed to have a good performance and be a simple. For example standard way to call something like `cell.stop()` etc. But we can't use classes. And removing cell inside the check is also the most effective way because it's one step action. For super big files, every function call counts.

Written above make the iteration protocol is more complex and complicate check writing. But it seems it's just a price for solving so complex problem with flexibility and performance in mind.

## Possible improvements

Like with the Error creation API here we could try to make thing a little bit more convenient.  I see the main problem with cell removing API:

```python
# One cell removal
def check(errors, cells, row_number):
  for cell in copy(cells):
   # Perform your check
   cells.remove(cell) # remove invalid
   
   
# All cells removal
def check(errors, cells, row_number):
  # Perform your check
  cells[:] # remove the row - THE UGLIEST one
```

It's just a Python syntax which is good but probably we could introduce some kind of helper. For example superclassing `cells` list to provide some methods like `cells.clear()`

Also checking for cell's key existence:

```python
def check(errors, cells, sample=None):
    for cell in cells:
        if 'header' in cell:
            # perform check
```

Could be probably some kind of helper like `cell_having(cell, ['header', 'value'])`. But we can't use `Cell` class here so it's also kinda ugly.

Again not sure about everything above because it could also mess the things instead of making it cleaner.

## Proposal 1

There is a Vitor's proposal of changes I'de like to ask him to write it up in comments because not fully got it at first place.

The most interesting idea I suppose making `row-number` as a part of `cell` dict.

## Proposal 2

I was thinking yesterday how we could improve some not looking good staff like `cells[:]`. But for now, can't really propose anything. On initial design phase, I've tried a lot of options so I'm not sure I could come up with something new at the moment.

## Conclusion

There are things that could be improved but it seems we need to brainstorm it. An important point here that the same as with Error creation API we should have in mind that we need to follow fully decoupled way (i.e. check-cell-error is fully decoupled) to preserve goodtables flexibility and scalability. Also, there are should be really good reasons to introduce breaking changes at the moment.

**Comment by roll** [comment]
@brew 
@vitorbaptista 
@amercader 
@akariv 
@pwalsh 
Goodtables update discussion.

**Comment by pwalsh** [comment]
@roll this issue is redundant - the [PR](https://github.com/frictionlessdata/goodtables-py/pull/240) has been open since December, and opening this extremely detailed epic is to me is completely the wrong approach, wasting time and energy.

I'm supportive of the changes made by @vitorbaptista on technical grounds from a high-level assessment, and in generally supporting his role as Engineering Lead at OKI.

Please address specific technical issues in the PR, and work towards what needs to be done to merge the changes. I recommend closing this issue.

**Comment by vitorbaptista** [comment]
To avoid repeating what we talked on https://github.com/frictionlessdata/goodtables-py/pull/240, I'm going to comment only on changes that aren't part of that PR.

> Here is used dict because it can't be class (performance reasons) and it can't be tuple/namedtuple (checks should be able to mutate the cell).

The checks need to alter the cells contents, but they don't need to be the same cells that were received as an argument. Using the `cells` as an input and output argument was a design decision. We could've instead done something like:

```python
def my_custom_check(cells):
    modified_cells = []
    errors = []
    for cell in cells:
        modified_cell = copy(cell)
        modified_cell['value'] = int(modified_cell['value'])
        modified_cells.append(cell)
    return modified_cells, errors
```

This has performance implications, as we're copying the cells dicts around. If the cells were `namedtuples`, we could do:

```python
def my_custom_check(cells):
    modified_cells = []
    errors = []
    for cell in cells:
        modified_cell = cell._replace(
            value=int(modified_cell.value)
        )
        modified_cells.append(cell)
    return modified_cells, errors
```

Which, although I'm not sure, might have better performance than copying dicts. The end goal is to have the checks as pure functions, using only its arguments (without modifying them).

To be clear, my PR doesn't achieve this goal, and I don't plan on adding it now (there are enough changes already). I commented here just to argue that we don't need to have output arguments.

**Comment by roll** [comment]
@vitorbaptista 
> Could you give me an example of such check?
So related to the check signature:

```python
def my_custom_check(errors, cells):
```

There are a lot very simple use cases when checks will require knowledge about previous errors:
- it could be statistical checks which require some kind of map-reduce functionality (errors for every row than reduce it on the table level check)
- it could be conditional checks which add an error only if there is no other type of error etc

That a really basic requirement for goodtables extensibility.

---

About copying cells in very check - TBH I don't see reasons to make goodtables slower. It seems there is no win. I mean yes at the moment there is a movement to make things idempotent and pure. I think it's great and should be used everything when possible. But it doesn't mean we need to use a steam-hammer to crack nuts. It's one of the options but it should not be some kind of idea fix to use it everywhere.

--- 

Also for example for PR you're proposing for future:

```
for check_func in check_funcs:
    errors += (check_func(cells) or [])
    for error in errors:
        if error.cell:
            cells.remove(error.cell)
```

But one of the basic requirements based on previous `goodtables` code and Data Quality Dashboard that not every error is terminating. That why a check makes a decision about removing cells but not a higher-level iterator.

---

@vitorbaptista 
Please get me right - I think your ideas are very interesting and well-motivated. But I would really like if you will hear my concerns here. TBH I'm not sure you have a full context for now to make fully informed decisions. This project just requires the full dive for a good amount of time to get into all small details. That's how I see it. I suppose the better way to evolve software is to gather feedback first, start new iterations of work e.g. some pilots when we will be in need to write e.g. next 30 checks. Analyse our experience with these new input knowledge and improve the protocol if needed. I really hope it could and should be improved. I've already had the same pattern for tabulator and datapackage. Making changes based on new requirements and usage experience - I think it's a good way.
