### ISSUE TITLE
Disable Row Limit?

### ISSUE THREAD

**Issue by hydrosquall** [frictionlessdata/goodtables-py#248]
Hi Team,

Thanks for the great work on this library!

I was wondering if there were any strong opinions about circumventing the "row limit" on a validator. My temporary fix can be to just provide a very large number, but I'd be interested in being able to pass in the boolean that let me run the inspection on the entire file.

If there's interest, I can file a PR that would add this option.

**Comment by hydrosquall** [comment]
Followup- this looks very similar to #230

**Comment by vitorbaptista** [comment]
Hey @hydrosquall, we haven't created a new release yet, but if you use the last version from master, you can set any limit to `-1` to disable them. If you can wait, we're planning on launching a new version soon (few days), otherwise you can use the version from master.

**Comment by hydrosquall** [comment]
@vitorbaptista : this is great news!! Thanks for the update.
