### ISSUE TITLE
Schema-valid check disabled?

### ISSUE THREAD

**Issue by hydrosquall** [frictionlessdata/goodtables-py#249]
When I tried to use the `schema-check` structural check, I got the following error:

```
goodtables.exceptions.GoodtablesException: Check "schema-error" is not registered
```

Looking at the `registry.py` reveals that the check was skipped based on a PR that closed last year by @roll .

https://github.com/frictionlessdata/goodtables-py/blob/1d53269b9969db16d5c18af1f9080aadcc8a652e/goodtables/registry.py#L135

Is it safe to remove the `continue`, or is it still necessary?

**Comment by roll** [comment]
@hydrosquall 
For now, schema validation always happens but it's not customizable.

**Comment by hydrosquall** [comment]
I see, makes sense @roll . This issue can probably be closed then, unless we want to add a note about this to the docs (if there isn't one already).

**Comment by roll** [comment]
@hydrosquall 
Thanks!
