### ISSUE TITLE
Required Check is Overloaded with Primary Key Check

### ISSUE THREAD

**Issue by hydrosquall** [frictionlessdata/goodtables-py#251]
I'm working with a messy public dataset where some of the fields that I'd consider part of the "primary key" for that row are null.

Unfortunately, even if I specify that this field's constraints as  `required: False`, because they are part of the primary key, they will throw an error because of the line below.

https://github.com/frictionlessdata/goodtables-py/blob/75c7f019b11ba4c6045bbb8338ecc60590a887d9/goodtables/checks/required_constraint.py#L24

Two possible ideas come to mind to resolve this:

1. Don't overload this check and remove the primary key test
2. Let a "required = False" override the primary key check

**Comment by vitorbaptista** [comment]
@hydrosquall Thanks for the issue report.

I implemented your 2nd idea on https://github.com/frictionlessdata/goodtables-py/pull/252, just pending review. In the future, I can see we removing this `primaryKey` check into its own check, but having it as part of the `required-constraint` is OK for now.

**Comment by hydrosquall** [comment]
Thanks @vitorbaptista

**Comment by vitorbaptista** [comment]
As we talked on #252, it's part of the SQL specification that primary keys are non-null, so closing this as a wontfix. I opened https://github.com/frictionlessdata/specs/issues/593 on the spec repository to discuss about how to allow composite unique keys.
