### ISSUE TITLE
`pandas.DataFrame` compatibility

### ISSUE THREAD

**Issue by Midnighter** [frictionlessdata/goodtables-py#259]
Hi,

I read in another #1 issue that you don't want to depend on pandas and I completely understand. However, it'd be amazing to be able to validate an in-memory pandas table. Obviously some checks would have to be disabled but it has several advantages:

1. I only need to load the table once using pandas rather first loading it for `validate` and afterwards for again in pandas.
2. In memory operations are particularly handy in web services where I receive tabular data over the wire. Writing to a temporary file just to validate seems so crude.

If I misunderstood the goodtables API and in-memory validation can already be done, I'm happy to be pointed at the relevant documentation.

**Comment by vitorbaptista** [comment]
@Midnighter Have you tried using the `.to_dict('records')` method of `pandas.DataFrame`? I haven't tested, but you should be able to validate a dataframe using `goodtables.validate(df.to_dict('records'))`

**Comment by roll** [comment]
@Midnighter 
Also, it should be possible to use data table without header just providing it with the `headers` argument:
```python
validate(data_without_headers, headers=['col1', 'col2',...]
```

You could take a look on all options `goodtables` inherit from `tabulator` here:
https://github.com/frictionlessdata/tabulator-py#streamsource-options

**Comment by Midnighter** [comment]
Just a heads-up that converting to dict may change order of the columns. So a safer approach is:

```python
records = df.to_dict("records")

validate(records, headers=list(records[0]), schema=schema)
```
