### ISSUE TITLE
format-error when inferring a CSV

### ISSUE THREAD

**Issue by vitorbaptista** [frictionlessdata/goodtables-py#260]
Try to run `goodtables infer` with the data from https://raw.githubusercontent.com/vitorbaptista/birmingham_schools/master/data/birmingham_schools.csv

**Comment by aborruso** [comment]
@vitorbaptista ho to do it?

I have run `goodtables --infer-schema birmingham_schools.csv` and I have no error. What am I doing wrong?

**Comment by roll** [comment]
Works for me also
