### ISSUE TITLE
Blank line handling differs from csv library

### ISSUE THREAD

**Issue by catherinedevlin** [frictionlessdata/goodtables-py#268]
While using goodtables, I ran into confusion because tabulator handles blank lines in a CSV differently than the Python standard library's `csv` module does.  `csv` ignores blank lines, but `tabulator` treats them as empty rows.  

This causes confusion when I try to match up the validation error messages from goodtables with the input sent in - if I use Python's CSV to interpret the source, its line numbers might not match the line numbers in the validation messages.  I can think of three approaches:

1. goodtables.validate accepts an an "ignore_blank" argument, passed on to tabulator (which will need a corresponding upstream change), so that its behavior can match csv's

2. goodtables.validate accepts a "return_rows" argument, so that its output includes not just the line number for each validation message, but the actual contents of that row - then 

3. Users of goodtables should know to use tabulator.Stream rather than csv when comparing a source csv to validator's output.  This is what I'll do for now (no code changes required) but people won't know they need to until they go down this rabbit hole as I did.

I've attached a zipfile with a sample CSV and a Jupyter notebook demonstrating the difference.

and here's the markdown export of it:

```
"Name","Title"
"Guido","BDFL"

"Catherine","DBA"
,
"Yoz","Engineer"
```

```python
import csv
with open('has-blanks.csv') as infile:
    reader = csv.DictReader(infile)
    result = list(reader)
result
```

    [OrderedDict([('Name', 'Guido'), ('Title', 'BDFL')]),
     OrderedDict([('Name', 'Catherine'), ('Title', 'DBA')]),
     OrderedDict([('Name', ''), ('Title', '')]),
     OrderedDict([('Name', 'Yoz'), ('Title', 'Engineer')])]

```python
from tabulator import Stream
stream = Stream('has-blanks.csv')
stream.open()
list(stream)
```

    [['Name', 'Title'],
     ['Guido', 'BDFL'],
     [],
     ['Catherine', 'DBA'],
     ['', ''],
     ['Yoz', 'Engineer']]

[blanks_in_csv.zip](https://github.com/frictionlessdata/goodtables-py/files/1917283/blanks_in_csv.zip)

**Comment by roll** [comment]
Sorry I missed this issue and it's probably not actual already.

But I'd recommend to use plain `csv.reader` reader instead for the keyed one `csv.DictReader`. In this case it will match `tabulator`'s output:

```python
import csv
with open('tmp/issue268.csv') as infile:
    reader = csv.reader(infile)
    result = list(reader)
print(result)
```
