### ISSUE TITLE
Report detected separator of an inspected CSV

### ISSUE THREAD

**Issue by aborruso** [frictionlessdata/goodtables-py#270]

**Comment by aborruso** [comment]
A way to do it - thank you @roll - is

```python
import csv
from datapackage import Resource
resource = Resource({u'path': 'input.csv'})
dialect = csv.Sniffer().sniff(resource.raw_read())
dialect.delimiter
```

The requirements: csv and datapackage-py modules

**Comment by roll** [comment]
MERGED into https://github.com/frictionlessdata/goodtables-py/issues/341

**Comment by aborruso** [comment]
Only a stupid note: I'm very happy to see the field separator in frictionless describe output, because without it you have (in my opinion) a big descriptive barrier.

Thank you very much
