### ISSUE TITLE
Incorrect detection of encoding gives out a source-error

### ISSUE THREAD

**Issue by augusto-herrmann** [frictionlessdata/goodtables-py#274]
We have a csv file that uses utf-8 encoding, but uses only ascii characters up to some point at the middle of the file. Goodtables is probably incorrectly interpreting it as an ascii file, because it gives out a source-error:

```
$ goodtables --infer-schema data/nz.csv 
DATASET
=======
{'error-count': 1,
 'preset': 'nested',
 'table-count': 1,
 'time': 0.003,
 'valid': False}

TABLE [1]
=========
{'error-count': 1,
 'headers': [],
 'row-count': 0,
 'source': 'data/nz.csv',
 'time': 0.002,
 'valid': False}
---------
[-,-] [source-error] 'charmap' codec can't decode byte 0x81 in position 1780: character maps to <undefined>
```
File: [data/nz.csv](/okfn/publicbodies/blob/master/data/nz.csv)

The line that gives an error is [L18](/okfn/publicbodies/blob/master/data/nz.csv#L18):

```
nz/archives-new-zealand-te-rua-mahara-o-te-kwanatanga,Archives New Zealand Te Rua Mahara o te Kāwanatanga,,,,,,,,,http://www.archives.govt.nz,NZ,,,,,
```
Apparently, this would have been fixed in #45 by implementing a `decode_strategy` keyword. But I could not find any mention of it in the documentation. The default settings still leave users of Goodtables confused.

**Comment by AntoineAugusti** [comment]
I'm having this issue with a UTF-8 CSV file, incorrectly parsed with an iso8859-1 encoding. It leads to an error.

What's the recommended way to deal with this?

**Comment by roll** [comment]
Hi @AntoineAugusti,

if you know an encoding in advance:

```
report = goodtables.validate(path, encoding='utf-8')
```

**Comment by AntoineAugusti** [comment]
```py
goodtables.validate(
    [{"source": "exemple-valide.csv", "schema": "schema.json"}], encoding="utf-8",
)
```

throws an exception
```
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    [{"source": "exemple-valide.csv", "schema": "schema.json"}], encoding="utf-8",
  File "/Users/antoineaugusti/Documents/consolidation-irve/venv/lib/python3.7/site-packages/goodtables/validate.py", line 80, in validate
    report = inspector.inspect(source, **options)
  File "/Users/antoineaugusti/Documents/consolidation-irve/venv/lib/python3.7/site-packages/goodtables/inspector.py", line 66, in inspect
    warnings, tables = preset_func(source, **options)
TypeError: nested() got an unexpected keyword argument 'encoding'
```

**Comment by roll** [comment]
Please try:

```
godotables.validate(source, schema=schema, encoding="utf-8")
# OR
goodtables.validate([{"source": "exemple-valide.csv", "schema": "schema.json", "encoding": "utf-8"}])
```

**Comment by roll** [comment]
For now, it works only if `encoding=utf-8` is provided. We're going to improve quality of detection here - https://github.com/frictionlessdata/tabulator-py/issues/308
