### ISSUE TITLE
How to write enumerable-constraint?

### ISSUE THREAD

**Issue by peterdesmet** [frictionlessdata/goodtables-py#276]
For [blacklisted-value](https://github.com/frictionlessdata/goodtables-py#blacklisted-value) it is documented that those values should be listed in the `blacklist` property, but how should values be provided to the `enumerable-constraint` or `minimum-constraint` etc.? I tried `values`, `value`, `list`, `enum`, but I never get any errors in the report (while I am expecting some), except for the `required-constraint`:

```python
from goodtables import validate
gt_specs = [
  {'required-constraint': {'column': 'occurrenceID'}},
  {'enumerable-constraint': {'column': 'countryCode', 'values': ['be', 'nl', 'fr'] }},
  {'minimum-constraint': {'column': 'individualCount', 'value': 2 }},
]
gt_report = validate(example_csv_file, checks=gt_specs, infer_schema=True, order_fields=True)
print(gt_report['tables'][0]['errors'])
```

Output:

```
[{'code': 'required-constraint', 'column-number': 23, 'row-number': 3, 'message': 'Column 23 is a required field, but row 3 has no value'}]
```

**Comment by roll** [comment]
@peterdesmet 
Hi, we have to use [Table Schema](https://frictionlessdata.io/specs/table-schema/) to provide constraints:
```
validate(data, schema={fields: [
  {name: field1, constraints: {enum: [value1, value2]}}
]}
```
