### ISSUE TITLE
false positive on unique constraint and column number issue

### ISSUE THREAD

**Issue by nathanxmeyer** [frictionlessdata/goodtables-py#277]
Hello,

I have a table schema (JSON) and a CSV file. Using Python tools for goodtables to validate, I get false errors on a GUID key.  Note, I do have another unique constraint on some files (the GUID is programmatically supplied but the user also supplies what should be an unique name) and have no problem with them, only with the GUID.

Also, when I evaluate the error report column number, it does not point to the correct column although I do correct for the difference in how column numbers are reported on the table versus the list object supplied in the report. 

Validation  JSON, CSV and the report JSON included. Code snippet pasted in. 
Appreciate the help.

report = validate(mytable, schema=myschema, order_fields=True)

if report['error-count'] == 0:
    pass
else:           
#handle if there were errors on the goodtables validate call

    errortxt = "D:/@ErrorReport.txt"

    # grab the error from report
    try:
        with open(errortxt, "a+") as ferr:
            myerror = report['tables']
            myerror = error[0]
            myheader = myerror['headers']
            ferr.write(myerror['source'])
            ferr.write("\n")
            myerrors = myerror['errors']
            for item in range(len(myerrors)):
                errordict = myerrors[item]
                ferr.write("\t" + "error type: " + errordict["code"] + "\n")
                # row-number includes header and starts count from 1 not 0
                myitem = tablelist[(errordict["row-number"]-2)]
                ferr.write("\t" + "iDig Object: " + myitem[0] + " - " + myitem[1] + " - " + myitem[2] + " - " + myitem[3] + "\n") 
                mycolumn = errordict["column-number"]
                # column numbers start at one whereas list starts at 0
                mycolumn = mycolumn - 1
                ferr.write("\t" + "field: " + myheader[mycolumn] + "\n")
                # note the test avoids a long ugly line for unique constraint violations
                ferr.write("\t" + "message: " + msg + "\n\n")

[validatetest.zip](https://github.com/frictionlessdata/goodtables-py/files/2365313/validatetest.zip)

**Comment by roll** [comment]
@nathanxmeyer 
Hi, I have downloaded the `validatetest.zip` and there are free files:
```
filldeposit.json
Stripped_D18-A3.Fills and Deposits.csv
Stripped_D18-A3.Fills and Deposits_Cleanse.JSON
```
I'd like to reproduce this issue but I have to know what exact files to used with `validate` function.

**Comment by nathanxmeyer** [comment]
Hi there, apologies for lack of clarity:

filldeposit.json = table schema

> Stripped_D18-A3.Fills and Deposits.csv = input CSV to be validated
> Stripped_D18-A3.Fills and Deposits_Cleanse.JSON = json dump of validation report. 



---Hug the ones you love---

**Comment by roll** [comment]
@nathanxmeyer 
Yea I see - it's weird. It seems UUID is column 56 but the errors in column 55.

I would try using `validate` without `order_fields=True` to debug it. Also trying to reduce columns count. It could be a problem with csv dialect - maybe we need to pass it explicitly to the `validate(separator=<>, etc)` (see https://github.com/frictionlessdata/tabulator-py#csv-read--write)

**Comment by roll** [comment]
It seems to have been fixed - https://github.com/frictionlessdata/goodtables-py/pull/366/files
