### ISSUE TITLE
How to use a localized spec.json?

### ISSUE THREAD

**Issue by pierredittgen** [frictionlessdata/goodtables-py#279]
Hi,

I work for a french OpenData project that helps people to check their CSV before publishing them online.
We use goodtables for this task, it works great! At this time, we would like to offer french error messages to the users.

We localized spec.json but how to use this localized version in goodtables-py project without patching the project?

**Comment by roll** [comment]
@pierredittgen 
I agree that custom spec should be a useful feature.

For now, I think we can overcome this limitation by updating `goodtables.spec`:
```
from goodtables import spec

spec['errors']['io-error']['message'] = 'New message'
```

**Comment by pierredittgen** [comment]
Ok. Thanks for this workaround!
