### ISSUE TITLE
Unclear error: Format "None" is not supported

### ISSUE THREAD

**Issue by ludovicc** [frictionlessdata/goodtables-py#281]
Hello, I'm trying to validate a CSV file using goodtables. The datapackage appears valid using 'data validate', but goodtables 2.1.0 fails on the same file.

```
~> data validate
> Your Data Package is valid!
~> goodtables .
DATASET
=======
{'error-count': 1,
 'preset': 'nested',
 'table-count': 1,
 'time': 0.004,
 'valid': False}

TABLE [1]
=========
{'error-count': 1,
 'headers': [],
 'row-count': 0,
 'source': '.',
 'time': 0.001,
 'valid': False}
---------
[-,-] [format-error] Format "None" is not supported
```
Files used:
datapackage.json: https://gist.github.com/ludovicc/96c90a29e8e324ca27b9fff7ae6a73b1
data.csv: https://github.com/LREN-CHUV/data-db-setup/blob/master/tests/one-dataset/sql/data.csv

Thanks

**Comment by roll** [comment]
@ludovicc 
Hi, try using (instead of a dot):

```bash
goodtables datapackage.json
```

Please re-open if it hasn't helped.

**Comment by jordan-dimov** [comment]
I too have this problem when reading from a file object, which otherwise contains a valid CSV:

```
> f = open('some.csv', 'r')
> validate(f)

{'time': 0.001,
 'valid': False,
 'error-count': 1,
 'table-count': 1,
 'tables': [{'time': 0.0,
   'valid': False,
   'error-count': 1,
   'row-count': 0,
   'source': 'inline',
   'headers': [],
   'errors': [{'code': 'format-error',
     'message': 'Format "None" is not supported',
     'message-data': {}}]}],
 'warnings': [],
 'preset': 'table'}

```
If instead I pass the filename to `validate`, I get different validation errors (that make a lot more sense than this and are actually expected - e.g. some blank columns and some blank rows). 

Unfortunately, my use case calls for using file objects, as the data does not come from actual files on the filesystem.

**Comment by roll** [comment]
@jordan-dimov 
`goodtables` (and `tabulator` under the hood) has no chance to detect what's format the file contents have. So it returns an error.

```
> f = open('some.csv', 'r')
> validate(f, format='csv')
```
