### ISSUE TITLE
Unique constraiant error message includes too many row numbers

### ISSUE THREAD

**Issue by jdaviscooke** [frictionlessdata/goodtables-py#291]
When validating data with a unique constraint, the error message will include all row numbers between the last valid row and the row that violates the constraint. 

See https://gist.github.com/jdaviscooke/9aa1f605a8fdd946c23bf023848d0843 for an example of how I am running into this error. 

I would expect to see that rows 4 and 10 violate the unique constraint, but instead I see
`
{
          "code": "unique-constraint",
          "row-number": 10,
          "column-number": 1,
          "message": "Rows 2, 3, 4, 5, 6, 7, 8, 9, 10 has unique constraint violation in column 1",
          "message-data": {
            "row_numbers": "2, 3, 4, 5, 6, 7, 8, 9, 10"
          }
        }
`
Happy to provide any additional detail that you need.

**Comment by roll** [comment]
@jdaviscooke 
Thanks. It seems a bug.
