### ISSUE TITLE
Make goodtables available via conda-forge

### ISSUE THREAD

**Issue by zaneselvans** [frictionlessdata/goodtables-py#299]
Is there a reason why goodtables isn't yet available via `conda-forge`? Soon it will be the only thing left in [our project](https://github.com/catalyst-cooperative/pudl) that has to be installed via `pip`.

**Comment by pwalsh** [comment]
Hey @zaneselvans !

I don't know anything about conda forge - how does a package get on it?

**Comment by zaneselvans** [comment]
I... don't really know, but all of the other frictionless data python tools that we're using are available via `conda-forge` already, so I suspect that someone here like @roll does know how it works.

**Comment by zaneselvans** [comment]
Outline of the conda-forge package contribution process [available here](https://conda-forge.org/docs/maintainer/adding_pkgs.html).

**Comment by roll** [comment]
@zaneselvans 
Thanks. I've added https://github.com/conda-forge/staged-recipes/pull/8532 based on the `datapackage` one. Let see how their systems work..

**Comment by roll** [comment]
Meta-issue for Anaconda publishing - https://github.com/frictionlessdata/implementations/issues/34
