### ISSUE TITLE
I'd like to join the maintainers team

### ISSUE THREAD

**Issue by cbenz** [frictionlessdata/goodtables-py#305]
After discussing with @rufuspollock I'd like to join the maintainers team of goodtables-py.

During the development of [Validata](https://git.opendatafrance.net/validata) with @pierredittgen I had the opportunity to submit some [issues](https://github.com/frictionlessdata/goodtables-py/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3Acbenz) and [PR](https://github.com/frictionlessdata/goodtables-py/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Acbenz+), and I'd like to continue contributing.

**Comment by lwinfree** [comment]
Hi @cbenz! That's great - we can always use more people willing to contribute :-) Let's pair you up with @roll who can answer questions you might have and provide help. Also please have @roll review any code changes. Thanks so much for your help!
