### ISSUE TITLE
Slow validation of large tables. Validate columns rather than cells?

### ISSUE THREAD

**Issue by ezwelty** [frictionlessdata/goodtables-py#307]
I was initially surprised by how slow content checks are for large tables, until I realized that checks are performed line by line and cell by cell, rather than by column. Have you considered taking advantage of fast, vectorized operations already available in python, R, etc to speed up validation?

The example below features a single table with one integer field and one million rows. `type-or-format-error` takes 19 seconds, whereas the equivalent (?) vectorized operations in python and R below (which read the data as strings and parse them to integer) take a fraction of a second.

### `goodtables-py`: 18.895 seconds

```python
import goodtables
report = goodtables.validate(
  'datapackage.json',
  row_limit=1000000,
  checks=['type-or-format-error'])
report['time']
```

### `pandas`: 0.629 seconds

```python
import pandas
import time
start = time.time()
df = pandas.read_csv('resource.csv', dtype=str)
result = df.id.astype(int)
time.time() - start
```

### `readr` (R): 0.207 seconds

```R
start <- Sys.time()
df <- readr::read_csv('~/repos/temp/resource.csv', col_types = 'c')
result <- readr::parse_integer(df$id)
Sys.time() - start
```

### `data.table` + `readr` (R): 0.135 seconds

```R
start <- Sys.time()
df <- data.table::fread(
  '~/repos/temp/resource.csv',
  stringsAsFactors = FALSE, colClasses = list(character = 'id'))
result <- readr::parse_integer(df$id)
Sys.time() - start
```

### Files

`datapackage.json`

```json
{
  "name": "package",
  "profile": "tabular-data-package",
  "resources": [
    {
      "name": "resource",
      "profile": "tabular-data-resource",
      "path": "resource.csv",
      "schema": {
        "fields": [
          {
            "name": "id",
            "type": "integer"
          }
        ]
      }
    }
  ]
}
```

`resource.csv` (1 million rows)

```
id
1
2
3
...
```

**Comment by roll** [comment]
Hi @ezwelty,

Thanks for the very useful information. It's something to think about. Not ready to discuss it yet but just curious how it could play with the way our stack treats any data - as a stream of lines without preserving anything in memory. 

I'm pretty sure also that `goodtables` is slow because we have some very ineffective cast functions.

**Comment by ezwelty** [comment]
Hi @roll,

Existing tools could easily be applied to file chunks to limit memory use to a reasonable maximum. Otherwise (and this is "above my pay grade"), I suppose it would be worth looking at pandas.read_csv, readr::read_csv, data.table::fread, etc under the hood to figure out why they are so fast. I believe they also work on a per-line basis, but in C. Some details are given for data.table::fread, the fastest of the bunch, at https://rdrr.io/cran/data.table/man/fread.html#heading-3.

For reference, another timing test, checking `resource.csv` with a regular expression:

```bash
time grep -v -E "^id$|^[0-9]+$" resource.csv
```

> real    0m0.628s
user    0m0.622s
sys     0m0.004s

p.s. How do you check uniqueness without storing anything in memory?

**Comment by ezwelty** [comment]
@roll Pandas creator Wes McKinney describes using Cython to speed up file reading and parsing values to numeric in a [blog post](https://wesmckinney.com/blog/speeding-up-pandass-file-parsers-with-cython/). Pandas' parsers are at [pandas-dev/pandas/io/parsers.py](https://github.com/pandas-dev/pandas/blob/master/pandas/io/parsers.py).

I've never worked with Cython, and I wanted a way to read, parse, and check large Tabular Data Packages very quickly, so I quickly threw this together for the time being. 

https://github.com/ezwelty/goodtables-pandas-py

It is about 100x faster on large data. Because the existing stack is built on a per-row data stream, I couldn't simply overload existing classes (Resource, Table, Storage, etc), so I wrote a standalone tool. Memory use could be greatly minimized by reading, parsing, and checking tables in chunks (using `pandas.read_csv(chunksize=)`), and storing only (unique) field values for unique and foreign key checks. That would provide the combined benefit of speed from vectorized calls to C, and limited memory use. I wonder how much faster goodtables can get operating row-by-row, cell-by-cell from within a Python environment.

**Comment by roll** [comment]
@ezwelty 
That's awesome!

I think we need to think have we can introduce these promising results into the FD stack. The problem that most of our tools are about reading data so e.g. `datapackage.resource.read` has to return data not columns for analysis. A few directions I can see:

- thinking about using `pandas.read_csv` as an additional `tabulator` parser. There is a question can pandas read and return data so quickly
- thinking about using it for datacasting in `tableschema`
- thinking about getting data from `pandas.read_csv` as a source for `goodtables.validate`

If these ideas will not work out (and I'm not sure they will because our tools need these row streams, not a data frame):

- consider having this `goodtables-pandas-py` (I would say more like `goodframes-py` =) as an alternative library implementing a subset of `goodtables` functionality (being compatible with the `goodtables` report format) written for speed. I guess we will run into a good deal of limitations like reporting exact row/col of bad type error etc but for really big data it will be a real breakthrough anyway.

WDYT?

**Comment by ezwelty** [comment]
@roll I'm not familiar enough with the stack requirements for reading, parsing, and streaming to say for sure whether pandas would provide much benefit to those steps. Where pandas clearly shines is where it can make use of numpy, namely casting field values and checking field and table constraints on numeric fields. There are many Table Schema that cannot be handled by `pandas.read_csv` internally, hence why `goodtables-pandas-py` first reads a table as a DataFrame of string fields, then parses and casts field values as a second step.

In the example below, pandas is slower at extracting a regex group (for bareNumber: false) for casting to integer than a plain python version because it is just a wrapper that returns the results in a new pandas Series. However, casting extracted strings to int is faster, and checking the resulting integers against minimum and maximum constraints is much faster.

```python
import pandas
import timeit

x = pandas.Series(range(10000000)).astype(str)

# ---- Extract integer characters from string (bareNumber: false) ----

def extract_integer():
  pattern = re.compile(r"(-?[0-9]+)")
  result = []
  for i, xi in x.iteritems():
    result.append(pattern.findall(xi)[0])

def extract_integer_vectorized():
    pattern = re.compile(r"(-?[0-9]+)")
    result = x.str.extract(pattern, expand=False)

timeit.timeit(extract_integer, number=1)
# 9.80 s
timeit.timeit(extract_integer_vectorized, number=1)
# 20.09 s (slower!)

# ---- Cast string to integer ----

def parse_integer():
  result = []
  for i, xi in x.iteritems():
    result.append(int(xi))

def parse_integer_vectorized():
    result = x.astype(int)

timeit.timeit(parse_integer, number=1)
# 5.67 s
timeit.timeit(parse_integer_vectorized, number=1)
# 1.25 s (faster!)

# ---- Check integer constraints ----

x = pandas.Series(range(10000000))

def check_integer():
    result = []
    for i, xi in x.iteritems():
        result.append(xi > 0 and xi < 9999999)

def check_integer_vectorized():
    result = (x > 0) & (x < 9999999)

timeit.timeit(check_integer, number=1)
# 3.77 s
timeit.timeit(check_integer_vectorized, number=1)
# 0.04 s (much faster!)
```

As you said, you'll want to profile `goodtables` up the chain of command to see whether the slowdowns are in reading files, parsing strings, casting strings to values, or checking constraints. If improvements can't be made upstream, having a faster subset of `goodtables` seems like a good plan. Perhaps the functionality for reading and casting Tabular Resources to a pandas DataFrame could exist in its own package (i.e. a faster version of `tableschema-pandas-py`).

Currently, `goodtables-pandas-py` reports one error with an array of the (unique) invalid values, but it would be easy enough to report (DataFrame) row numbers. With large datasets, I don't think it makes sense to add an error for each invalid value, since the error list can become gigantic and completely unreadable, but I suppose that could be done to fit the existing report format.

**Comment by roll** [comment]
Hi @ezwelty 

I'm closing it as we can't move to column-based validation in general as the whole FD infrastructure is based on row-streams.

It doesn't mean we can't improve the situation:
- in #341 I'm going to improve performance as much as possible. I ran some tests (actually for another project in JavaScript but it doesn't matter) which showed that even row-based validation can be extremely fast (comparable to `pandas.read_csv`) if checks/cast-functions are optimized
- I've added the link to `goodtables-pandas-py` to the readme as faster Pandas-specific based alternative
