### ISSUE TITLE
Additional arguments to custom checks

### ISSUE THREAD

**Issue by Midnighter** [frictionlessdata/goodtables-py#308]
Hi,

I would like to pass an argument to one of my custom checks. I was expecting an API similar to the advanced checks to work, for example, let's say I want to implement a membership test. The blacklist can be called like:

```py
from goodtables import validate

report = validate('data.csv', checks=[
    {'blacklisted-value': {'column': 'name', 'blacklist': ['bug', 'bad']}},
])
```

So what I tried was:

```py
@check('color-check', type='custom', context='body')
def custom_check(cells, colors):
    errors = []
    for cell in cells:
        if cell['value'] not in colors:
            message = 'Unknown color {value} on column {column_number} and row {row_number}'
            error = Error(
                'color-error',
                cell,
                message
            )
            errors.append(error)
    return errors

report = validate('data.csv', checks=[
    {'color-check': {'colors': ['red', 'green']}},
])
```

Is this possible at all? Am I missing something obvious?

**Comment by roll** [comment]
Hi, please take a look at the class-based check implementations - contribute/checks/deviated-value eg

**Comment by Midnighter** [comment]
Cool, https://github.com/frictionlessdata/goodtables-py/blob/master/goodtables/contrib/checks/blacklisted_value.py was a good example for me.
