### ISSUE TITLE
Support PIP305 Quoting

### ISSUE THREAD

**Issue by andrejjh** [frictionlessdata/goodtables-py#309]
This is a suggestion to extend CSV Dialect in order to support the PIP305 quoting parameter.
eg quoting = QUOTE_NONE
For the moment, this is not taken into account and goodtables always returns 'quotechar must be set if quoting enabled'

**Comment by roll** [comment]
FIXED in https://github.com/frictionlessdata/tabulator-py/commit/314ba6e07f1ed76ab56628336e83c33f303457f9
