### ISSUE TITLE
Possibly incorrect inclusion of statistics package in setup.py

### ISSUE THREAD

**Issue by zaneselvans** [frictionlessdata/goodtables-py#311]
In re-organizing our conda environments, I've noticed that a package called `statistics` is getting installed from PyPI sometimes -- when everything we're installing should be available from `conda-forge`.  The version that's getting installed is 1.0.3.5. It's getting installed because it's listed as a requirement for `goodtables`.  The package is being used within goodtables in the `deviated_value.py` module... to calculate standard deviations, mean, median etc.  Seems reasonable.

Except that... the `statistics` module that's getting installed and which is referred to in the goodtables `setup.py` *appears* to be [this one](https://pypi.org/project/statistics/), last updated in 2014 -- a port to Python 2 of some PyPI download statistics functionality from Python 3.  Which seems wrong.

Not sure if/how the calculation of those statistical things could be working in `deviated_value.py`

**Comment by roll** [comment]
Sorry, I finally got to it. 

So, yes, we use this backport to provide the same functionality for Python2. 

I would handle this one as `wontfix` for now because Python2 will be done in 3 months. Then we can drop all our backports. 

Please re-open if you think we still can do something now.
