### ISSUE TITLE
None of header validators(inbuilt and custom that has context="head") are invoked if there is a blank header

### ISSUE THREAD

**Issue by SrividhyaGuru** [frictionlessdata/goodtables-py#312]
# Overview

If the excel has a blank header column in between, none of the validations for headers are triggered.

```
report = validate(file_path, skip_rows=[1, 2, 3, 4], checks=[
        'blank-header', 'missing_header_check', 'duplicate-header'
    ])
```
<img width="731" alt="Screenshot 2019-10-09 at 6 46 07 PM" src="https://user-images.githubusercontent.com/24490498/66484867-70985880-eac5-11e9-92c7-9137f4e43289.png">

Since 5th column is having blank headers, we wanted to see the blank header validator report that but it did not. Also we had **missing_header_check** that is custom built check that has context="head". But **missing_header_check** also did not kick in.

---

Please preserve this line to notify the @frictionlessdata/python team

**Comment by roll** [comment]
@SrividhyaGuru 
Could you please share some file without real data that breaks `goodtables` that way?

**Comment by SrividhyaGuru** [comment]
Schema used:
```{
  "fields": [
    {
      "name": "Column_1",
      "title": "Column_1",
      "type": "string",
      "description": "Sample Column_1",
      "constraints": {
        "required": true
      }
    },
    {
      "name": "Column_2",
      "title": "Column_2",
      "type": "string",
      "description": "Sample Column_2",
      "constraints": {
        "required": true
      }
    },
    {
      "name": "Column_3",
      "title": "Column_3",
      "type": "string",
      "description": "Sample Column_3",
      "constraints": {
        "required": true
      }
    },
    {
      "name": "Column_4",
      "title": "Column_4",
      "type": "string",
      "description": "Sample Column_4",
      "constraints": {
        "required": true
      }
    }
  ]
}
```

The following excel is missing a column **Column_4** that is mentioned in schema. The excel has an extra header **Column_5** which is not mentioned in the schema. And **the excel is having a blank header in column D**

[missing_column4_and_extra_header_column5.xlsx](https://github.com/frictionlessdata/goodtables-py/files/3713928/missing_column4_and_extra_header_column5.xlsx)

Running validate with the above mentioned excel with the above mentioned schema with checks as
`checks=["missing-header", "blank-header", "non-matching-header"]`
yields the following report:

```{'error-count': 0,
 'preset': 'table',
 'table-count': 1,
 'tables': [{'error-count': 0,
             'errors': [],
             'format': 'xlsx',
             'headers': ['Column_1', 'Column_2', 'Column_3', 'Column_5'],
             'row-count': 3,
             'schema': 'table-schema',
             'scheme': 'file',
             'source': 'missing_column4_and_extra_header_column5.xlsx',
             'time': 0.011,
             'valid': True}],
 'time': 0.105,
 'valid': True,
 'warnings': []}
```
@roll In **inspector.py** the header checks(the checks with `context='head`) is triggered only when the `has_headers` is true. 
But the `has_headers` is derived as follows:
```has_headers = (None not in headers)```

So if there are any blank headers in the excel, none of the header checks are running

Thanks

**Comment by roll** [comment]
Thanks, it seems a bug. 

BTW feel to PR if you have found a cause of this.

I'll debug as soon as I can
