### ISSUE TITLE
Schema checks are failing because schema is not properly mapped to the table columns 

### ISSUE THREAD

**Issue by SrividhyaGuru** [frictionlessdata/goodtables-py#313]
# Overview

Schema defined is not getting mapped properly to the corresponding columns when the column order in excel is not the same as the fields order mentioned in schema. Because of this incorrect mapping, schema errors are getting reported for wrong columns. 

Schema used:
```
{
  "fields": [
    {
      "name": "Column_1",
      "title": "Column_1",
      "type": "string",
      "description": "Sample Column_1",
      "constraints": {
        "required": false
      }
    },
    {
      "name": "Column_2",
      "title": "Column_2",
      "type": "string",
      "description": "Sample Column_2",
      "constraints": {
        "required": true
      }
    },
    {
      "name": "Column_3",
      "title": "Column_3",
      "type": "string",
      "description": "Sample Column_3",
      "constraints": {
        "required": false
      }
    },
    {
      "name": "Column_4",
      "title": "Column_4",
      "type": "string",
      "description": "Sample Column_4",
      "constraints": {
        "required": false
      }
    },
    {
      "name": "Column_5",
      "title": "Column_5",
      "type": "string",
      "description": "Sample Column_5",
      "constraints": {
        "required": false
      }
    }
  ]
}
```

Please note that in the above schema Column_2 has a `required = true` constraint and rest of the columns are `required = false`

Excel Used:
[sheet_with_different_header_order_than_schema.xlsx](https://github.com/frictionlessdata/goodtables-py/files/3717963/sheet_with_different_header_order_than_schema.xlsx)

The above attached excel has missing value in **Column_3 in row 3** and **not in Column_2**

But, running validate with the excel above and with the schema mentioned above as
```validate("sheet_with_different_header_order_than_schema.xlsx", order_fields=True, schema=SAMPLE_SCHEMA, checks=["required-constraint"])``` is giving the following report.

Report:
```
{'error-count': 1,
 'preset': 'table',
 'table-count': 1,
 'tables': [{'error-count': 1,
             'errors': [{'code': 'required-constraint',
                         'column-number': 2,
                         'message': 'Column 2 is a required field, but row 3 '
                                    'has no value',
                         'message-data': {},
                         'row-number': 3}],
             'format': 'xlsx',
             'headers': ['Column_1',
                         'Column_3',
                         'Column_2',
                         'Column_4',
                         'Column_5'],
             'row-count': 3,
             'schema': 'table-schema',
             'scheme': 'file',
             'source': 'sheet_with_different_header_order_than_schema.xlsx',
             'time': 0.016,
             'valid': False}],
 'time': 0.105,
 'valid': False,
 'warnings': []}
```

`order_fields=True` or `order_fields=False` does not have any difference in the report.

---

Please preserve this line to notify the @frictionlessdata/python team

**Comment by roll** [comment]
Hi @SrividhyaGuru,

I figured out the problem - for now, field ordering requires the `non-matching-header` check to be enabled. Here is how to make your code snippet work - https://github.com/frictionlessdata/goodtables-py/pull/361/files

I'm about to start working on the next version of `goodtables` (https://github.com/frictionlessdata/goodtables-py/issues/341) where this confusing behavior will be dropped and fields ordering will be independent to checks.
