### ISSUE TITLE
json compliant output

### ISSUE THREAD

**Issue by jhpoelen** [frictionlessdata/goodtables-py#327]
Currently, a table like:

one | two
-- | --
oneValue | twoValue

creates:
```
$ goodtables table.tsv 
DATASET
=======
{'error-count': 0,
 'preset': 'nested',
 'table-count': 1,
 'time': 0.102,
 'valid': True}

TABLE [1]
=========
{'encoding': 'utf-8',
 'error-count': 0,
 'format': 'tsv',
 'headers': ['one', 'two'],
 'row-count': 2,
 'scheme': 'file',
 'source': 'hello.tsv',
 'time': 0.003,
 'valid': True}
```

But, the output is not json, so ```goodtables table.tsv | jq .``` produces:

```
$ goodtables hello.tsv | jq .
parse error: Invalid numeric literal at line 2, column 0
```

With valid json input, the validation reports can be re-used by downstream programs. 

This is why I'd like to suggest to make goodtables produce json complliant output.

**Comment by roll** [comment]
@jhpoelen 
It seems the option is missing in the CLI help message:
```
goodtables data/valid.csv --json
```

**Comment by jhpoelen** [comment]
Nice! 

```
$ goodtables hello.tsv --json | jq . 
{
  "time": 0.102,
  "valid": true,
  "error-count": 0,
  "table-count": 1,
  "tables": [
    {
      "time": 0.004,
      "valid": true,
      "error-count": 0,
      "row-count": 2,
      "source": "hello.tsv",
      "headers": [
        "one",
        "two"
      ],
      "scheme": "file",
      "format": "tsv",
      "encoding": "utf-8",
      "errors": []
    }
  ],
  "warnings": [],
  "preset": "nested"
}
```

Why not make json formatted output a default?

**Comment by roll** [comment]
It's a common pattern when by default the output is human-readable and there are CLI options to format it one way or another. I think the majority of every-day dev tools like git/aws-cli/testeers/linters/etc use it

**Comment by jhpoelen** [comment]
Ok, good to know. I would suggest to add the --json option to the usage/help text.

**Comment by roll** [comment]
Thanks! Created an issue - https://github.com/frictionlessdata/goodtables-py/issues/328
