### ISSUE TITLE
Duplicate row bug

### ISSUE THREAD

**Issue by rudiharms** [frictionlessdata/goodtables-py#329]
# Overview

When running the validate on the Python3.7 (32 bit) environment it produces duplicate row errors which are incorrect. On the 64 bit python the validation runs fine, as it should.

The file has 160 000 rows.
You can use my schema to create a file : https://www.medicalschemes.com/xmlschemas/dddr/2019/JsonDDDRPartYearReturnTypeCC3_2019_8.json 
 validate(r'**file', schema=r'**schema',error_limit=30,row_limit=1000000)

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Hi @rudiharms,

can you share some dummy data to reproduce?

**Comment by rudiharms** [comment]
[testduplicate.zip](https://github.com/frictionlessdata/goodtables-py/files/4219360/testduplicate.zip)
[DDDRjsonValidateTest.zip](https://github.com/frictionlessdata/goodtables-py/files/4219391/DDDRjsonValidateTest.zip)

Hi,
i uploaded a file with testdata and the python script i use to validate. On the Python 3.7 32 bit  it incorrectly produces duplicate row errors.

**Comment by roll** [comment]
@rudiharms 
Thanks!

I'm marking this issue as help wanted because surprisingly there is no way to set up a 32-bit machine on Travis

**Comment by davidpeckham** [comment]
DuplicateRow.check_row() uses Python hash(), which yields hash collisions for @rudiharm's CSV on 32-bit systems:

    @check('duplicate-row')
    class DuplicateRow(object):

        # Public

        def __init__(self, **options):
            self.__row_index = {}

        def check_row(self, cells):
            errors = []

            # Get pointer
            try:
                pointer = hash(json.dumps(list(cell.get('value') for cell in cells)))
                references = self.__row_index.setdefault(pointer, [])

### Python 2.7.17, Docker arm32v7/python:2-alpine

I used a 32-bit Docker image to reproduce this:

    % goodtables validate --schema JsonDDDRPartYearReturnTypeCC3_2019_8.json testduplicate.csv

    DATASET
    =======
    {u'error-count': 2,
     u'preset': u'nested',
     u'table-count': 1,
     u'time': 919.862,
     u'valid': False}

    TABLE [1]
    =========
    {u'encoding': 'utf-8-sig',
     u'error-count': 2,
     u'format': 'csv',
     u'headers': [u'YearOfSubmission',
                  u'Part',
                  u'RefNo',
                  u'BenefitOptionNumber',
                  u'FinancialYear',
                  u'UniquePersonID',
                  u'MemberNumber',
                  u'DependantCode',
                  u'AuthEndDate',
                  u'AuthStartDate',
                  u'ICD10RegCDL'],
     u'row-count': 133487,
     u'schema': u'table-schema',
     u'scheme': u'file',
     u'source': 'testduplicate.csv',
     u'time': 919.097,
     u'valid': False}
    ---------
    [120930,-] [duplicate-row] Row 120930 is duplicated to row(s) 78028
    [121849,-] [duplicate-row] Row 121849 is duplicated to row(s) 113242

### Python 3.8.2, macOS 10.15.4

For comparison, here are results on 64-bit Python:

    % goodtables validate --schema JsonDDDRPartYearReturnTypeCC3_2019_8.json testduplicate.csv

    DATASET
    =======
    {'error-count': 0,
     'preset': 'nested',
     'table-count': 1,
     'time': 28.82,
     'valid': True}

    TABLE [1]
    =========
    {'encoding': 'utf-8-sig',
     'error-count': 0,
     'format': 'csv',
     'headers': ['YearOfSubmission',
                 'Part',
                 'RefNo',
                 'BenefitOptionNumber',
                 'FinancialYear',
                 'UniquePersonID',
                 'MemberNumber',
                 'DependantCode',
                 'AuthEndDate',
                 'AuthStartDate',
                 'ICD10RegCDL'],
     'row-count': 133487,
     'schema': 'table-schema',
     'scheme': 'file',
     'source': 'testduplicate.csv',
     'time': 28.768,
     'valid': True}

Here are the rows that cause hash collisions:

    import json

    row78028  = "2019|CC3|3315|2171|2018|BM48141601|481416|01|2018-01-01|2021-01-01|H40.9"
    row120930 = "2019|CC3|3315|2170|2018|BM1766066701|17660667|01|2018-01-01|2021-01-01|I10"

    print(hash(json.dumps(row78028.split("|"))))
    print(hash(json.dumps(row120930.split("|"))))

    row113242 = "2019|CC3|3315|2173|2018|BM1696959100|16969591|00|2018-01-01|2021-01-01|E78.5"
    row121849 = "2019|CC3|3315|2173|2018|BM1091337301|10913373|01|2018-08-24|2020-01-01|I10"

    print(hash(json.dumps(row113242.split("|"))))
    print(hash(json.dumps(row121849.split("|"))))

64-bit Python yields this:

    5432153924718808121
    7794690780065791934
    -7631044066816910336
    7435514060899188284

But 32-bit Python yields this:

    -1962801879
    -1962801879
    691905159
    691905159

Updating check_row() to hash the cell length as well as value may be the easiest way to resolve this:

    values = list(cell.get('value') for cell in cells)
    pointer = hash(json.dumps(list(str(len(value))+value for value in values)))

Or choose a hashlib hash function with a lower probability of collisions.

@roll, what do you think?

**Comment by roll** [comment]
Thanks @davidpeckham,

I'm going to switch the hashing function in https://github.com/frictionlessdata/goodtables-py/issues/341 (and rework `duplicate-row` in general)

For now, using a row length feels a good solution. I'll create a PR
