### ISSUE TITLE
Field Larger than field limit (131072)

### ISSUE THREAD

**Issue by rudiharms** [frictionlessdata/goodtables-py#330]
# Overview

I'm getting the error : Filed larger than field limit (131072) on a file structure check. Strange error. I checked the file and can't figure out what causes this. 
Googling it says its somehow related to the csv library which might be used in tabulator somewhere?
https://stackoverflow.com/questions/15063936/csv-error-field-larger-than-field-limit-131072 

I addded the test file and code i use to validate.

[DDDRjsonValidateTest - Copy.zip](https://github.com/frictionlessdata/goodtables-py/files/4254154/DDDRjsonValidateTest.-.Copy.zip)
[FieldLimitTest.zip](https://github.com/frictionlessdata/goodtables-py/files/4254155/FieldLimitTest.zip)

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Hi @rudiharms 

I would suggest

```
import sys
import csv

csv.field_size_limit(sys.maxsize)
```

from the discussion, you linked.

Please re-open if it doesn't help

**Comment by rudiharms** [comment]
Hi Thanks. The issue is an unclosed quotation mark in the csv causes this error in the python library.
Currently i have to first fix the csv that i receive from the client, by removing unclosed quotation marks, and only then can I pass it into goodtables.
Is there a way for goodtables to ignore those somehow maybe?

**Comment by roll** [comment]
@rudiharms 
You can pass csv options (https://docs.python.org/3/library/csv.html#dialects-and-formatting-parameters) to the validate function e.g.:

```python
goodtables.validate(source, doublequote=False)
```
