### ISSUE TITLE
Unique constraint applied to wrong column

### ISSUE THREAD

**Issue by AntoineAugusti** [frictionlessdata/goodtables-py#332]
# Overview
When validating a CSV against a schema, a unique constraint is wrongly applied to a column in the schema. This column is not listed as a primary key and does not have the `unique` constraint.

It happens for the column 12, `puiss_max`. The column just before, `id_pdc` is listed as a primary key. This issues happens for other columns as well.

## Files
- Schema: https://schema.data.gouv.fr/schemas/etalab/schema-irve/1.0.2/schema.json
- CSV file: [bornes.csv](https://gist.githubusercontent.com/AntoineAugusti/1bfb0c54693128ffd457005a4911dd7c/raw/072b442fc9b077ccb53fb61c8c429a8e80653032/bornes.csv)

Demo:
For column 12
```
$ goodtables validate --schema https://schema.data.gouv.fr/schemas/etalab/schema-irve/1.0.2/schema.json https://gist.githubusercontent.com/AntoineAugusti/1bfb0c54693128ffd457005a4911dd7c/raw/072b442fc9b077ccb53fb61c8c429a8e80653032/bornes.csv | grep "unique constraint violation in column 12" | wc -l
    2056
```

For column 13
```
$ goodtables validate --schema https://schema.data.gouv.fr/schemas/etalab/schema-irve/1.0.2/schema.json https://gist.githubusercontent.com/AntoineAugusti/1bfb0c54693128ffd457005a4911dd7c/raw/072b442fc9b077ccb53fb61c8c429a8e80653032/bornes.csv | grep "unique constraint violation in column 14" | wc -l
      499
```

For column 14
```
$ goodtables validate --schema https://schema.data.gouv.fr/schemas/etalab/schema-irve/1.0.2/schema.json https://gist.githubusercontent.com/AntoineAugusti/1bfb0c54693128ffd457005a4911dd7c/raw/072b442fc9b077ccb53fb61c8c429a8e80653032/bornes.csv | grep "unique constraint violation in column 14" | wc -l
      21
```

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Thanks for reporting @AntoineAugusti 

It must be a bug

**Comment by AntoineAugusti** [comment]
May be related to #277
