### ISSUE TITLE
compare date columns in csv using custom-contraints

### ISSUE THREAD

**Issue by aniket-savanand** [frictionlessdata/goodtables-py#335]
# Overview

## How do I use custom-contraint if I want to compare two dates columns in the csv?
e.g.
```
validate('example.csv',
                  checks=[
                      {'custom-constraint': {'constraint': 'date1column >= date2column'}}
                  ])
```
---
Please preserve this line to notify @roll (lead of this repository)

**Comment by AntoineAugusti** [comment]
`custom-constraint` does not handle casting. You may want to implement a custom check: https://github.com/frictionlessdata/goodtables-py#how-can-i-add-a-new-custom-check

**Comment by roll** [comment]
@aniket-savanand 
I agree with @AntoineAugusti, a custom check is to be used for the case. You can take a look at the `goodtables/checks` or `goodtables/contrib/checks` module for inspiration
