### ISSUE TITLE
Return python objects from validate

### ISSUE THREAD

**Issue by pganesh** [frictionlessdata/goodtables-py#351]
# Overview

Hi

We are validating a CSV file using the json schema. Everything works great.

But I need to get back each cell on the CSV as the appropriate python object type - is there an easy way to do this?

for example if the json table schema has two fields:

                    {
                        "name": "Invoice Date",
                        "type": "date",
                        "format": "%m/%d/%y"
                    },
                    {
                        "name": "Amount",
                        "type": "number",
                        "format": "default",
                        "BareNumber": "false",                      
                        "GroupChar": ",",
                        "DecimalChar": "."
                    }

And I have a CSV file like this:
04/30/19,"1,250,000.29"

it will validate great, but in my calling code, I'd like to get access to the python object with the right data types already that were "cast" to in order to validate

so I'd like to say 
<Invoice_date_python_date_object>,<Number_python_object>

this way, we don't have to parse the string data in the CSV file again for downstream processing.

any help is greatly appreciated!
---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Hi @pganesh,

That's for sure you can do it. For example, you can use `tableschema.Table` class to read cast data from csv - https://github.com/frictionlessdata/tableschema-py#working-with-table
