### ISSUE TITLE
Tableschema spec for groupChar, decimalChar and bareNumber

### ISSUE THREAD

**Issue by pganesh** [frictionlessdata/goodtables-py#352]
# Overview

When I use tableschema.py, I can use a json file for a number like this:
                        "type": "number",
                        "format": "default",
                        "bareNumber": "false",                      
                        "groupChar": ",",
                        "decimalChar": "."

It parses and validated correctly

But in goodtables-py this failed with the following error:

\'bareNumber\': \'false\', \'groupChar\': \',\', \'decimalChar\': \'.\'} is not valid under any of the given schemas at "fields/3" in descriptor

it looks like a version issue of some sort? If I make it BareNumber, GroupChar, DecimalChar etc. then it parses OK BUT the validation is not performed correctly.

Appreciate your help!

Using goodtables 2.4.12
Using tableschema 1.15.3

Also, if bareNumber = false, is goodtables supposed to strip out all leading/trailing characters?
---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
@pganesh 
Could you please share the exact code you run?

Tryin to guess you use case I think it should be something like this:

```
from goodtablas import validate
from tableschema import Table

source = 'path/to/the/file.csv'
schema = {
  "fields": [
     {"name": "number", "bareNumber": "false", "groupChar": ",", "decimalChar": "." },
     ... 
  ]
}

# goodtables
report = validate(source, schema=schema)

# tableschema
table = Table(source, schema=schema)
rows = table.read()
```

Please re-open if it didn't help
