### ISSUE TITLE
Custom check context "table"

### ISSUE THREAD

**Issue by cschloer** [frictionlessdata/goodtables-py#368]
# Overview

Hey, it looks like in the spec there is concept of a check having a context of "table". I assume that means it can check both the header and the body.

Currently with custom checks you can only register a check with context header or context body. I have a custom check where I want it to check both the header and the body (I'm creating a check class and I want both the check_headers and check_rows functions to be called)

Is there any way to do this?
---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
@cschloer 
I'm not sure whether it's possible now. 

I'm starting - https://github.com/frictionlessdata/goodtables-py/issues/341 - where this custom checks system will be fixed

MERGED into #341
