### ISSUE TITLE
Default TSV interpretation not what I was expecting

### ISSUE THREAD

**Issue by mccalluc** [frictionlessdata/goodtables-py#370]
# Overview

I had assumed that TSVs would be interpreted in line with the [`excel_tab` dialect](https://docs.python.org/3/library/csv.html#csv.excel_tab) but this is not the case. In particular, stray backslashes are ignored. Everything else was working beautifully, so it took us a while to notice these bad characters were getting in, and then some more time to fix it.

For us, it would have been better to have `excel_tab` as the default behavior for TSVs. If that's not possible, just having this issue around might help someone that runs into the same problem. Thank you for this library!

<details><summary>Reproducer</summary>

```python
#!/usr/bin/env python3
from tableschema import Schema
from goodtables import validate
from pprint import pprint
from csv import DictReader

path = '/tmp/test.tsv'
with open(path, 'w') as f:
    f.write('id\tdotted\n')
    f.write('1\tnot good\n')
    f.write('2\tstill\\.no\n')
    f.write('3\tshould.work\n')
    f.write('4\t"quotes.good"\n')

print('Expected parse:')
with open(path, encoding='latin-1') as f:
    reader = DictReader(f, dialect='excel-tab')
    for row in reader:
        pprint(dict(row))

descriptor = {'fields': [
    {'name': 'id',
     'type': 'number'},
    {'name': 'dotted',
     'constraints': {'pattern': r'\w+\.\w+'}}]}

print('\nDefault:')
report = validate(path, schema=descriptor)
for e in report['tables'][0]['errors']:
    print(e['message'])

print('\nWith "format" and "delimiter":')
report = validate(path, schema=descriptor, format='csv', delimiter='\t')
for e in report['tables'][0]['errors']:
    print(e['message'])
```

</details>

<details><summary>Output</summary>

```
Expected parse:
{'dotted': 'not good', 'id': '1'}
{'dotted': 'still\\.no', 'id': '2'}
{'dotted': 'should.work', 'id': '3'}
{'dotted': 'quotes.good', 'id': '4'}

Default:
The value "not good" in row 2 and column 2 does not conform to the pattern constraint of "\w+\.\w+"
The value ""quotes.good"" in row 5 and column 2 does not conform to the pattern constraint of "\w+\.\w+"

With "format" and "delimiter":
The value "not good" in row 2 and column 2 does not conform to the pattern constraint of "\w+\.\w+"
The value "still\.no" in row 3 and column 2 does not conform to the pattern constraint of "\w+\.\w+"
```

</details>

Related issues: 
- https://github.com/frictionlessdata/tabulator-py/issues/231 : points to Linear TSV as the TSV interpretation.
- https://github.com/frictionlessdata/goodtables-py/issues/14: Suggests that dialect be configurable.

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Hi @mccalluc,

I think the only thing you need is to set the format to `csv` so it will be handled by https://docs.python.org/3/library/csv.html not by https://github.com/solidsnack/tsv:

```pyhton
goodtables.validate('path.tsv', format='csv', delimiter='\t')
```

Please re-open if it didn't help
