### ISSUE TITLE
error: "The data source has not supported or has inconsistent contents; no tabular data can be extracted"

### ISSUE THREAD

**Issue by kgeographer** [frictionlessdata/goodtables-py#378]
# Overview

Trying to validate a utf-8 TSV file with 19k rows, and getting the error "The data source has not supported or has inconsistent contents; no tabular data can be extracted." 

The file loads as delimited file in excel, looks fine with 4 columns and the correct number of tab characters. Many other similar files are validating correctly in my app.

If I split the file, taking the first 300, or 600 rows, or the next 1000, it validates fine -- so it seems one bad line below that is stopping it (or the first bad line). But how can I find which line fails?

thanks

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Hi @kgeographer,

I think `report['tables'][0]['row-count']` should indicate the row number before the error in this case
