### ISSUE TITLE
Mistake in example used in documentation

### ISSUE THREAD

**Issue by brianmcdonald** [frictionlessdata/goodtables-py#383]
# Overview

I think the example in the custom constraint in documentation should read 

> "# error on row **3** with code "custom-constraint" 

instead of

>  "# error on row 4 with code "custom-constraint"

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Hi thanks,

It's actually correct in goodtables terms ( row at line 4). Terminology is quite confusing so  the new frictionless-py lib uses position word
