### ISSUE TITLE
Create system for help docs

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/goodtables-py#46]
Users should be able to contribute to creating help docs that correspond with errors we throw in the pipeline.

these docs can be shown on the web via the contextual help in goodtables-web. This has been somewhat stubbed out there.

Actions:

* [ ] Create a new repo for content only (goodtables-handbook, goodtables-help, etc.)
* [ ] Have a markdown docs that corresponds with the ID of each error in goodtables
* [ ] pull the markdown content in as the help content for the errors
* [ ] take this chance to tidy up the report result types a bit - e.g.: use sequential names "schema_001", "structure_014", etc.

**Comment by roll** [comment]
MOVED
https://github.com/frictionlessdata/data-quality-spec/issues/5
