### ISSUE TITLE
The improbability of being able to valid a date/time/datetime format if the source is excel

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/goodtables-py#49]
When the source is Excel, we use xlrd's stuff to turn Excel's number formatting for dates into Python dates. At the time of converting the excel source into a text stream for use in goodtables, we don't know if there is a schema, or what the formatting of a date should be according to the schema. So, the date is forced to isoformat.

That means that later on, the only way that a date/time/datetime field from excel will pass its schema validation is if the `format` is set to any.

Just putting this here for future.

**Comment by roll** [comment]
MOVED
https://github.com/frictionlessdata/implementations/issues/23

This issue moved to general issue tracker because it affects different level. And my guess it should be a `tabulator` updated if needed.
