### ISSUE TITLE
Implement Missing JTS Constraints

### ISSUE THREAD

**Issue by cspencer51** [frictionlessdata/goodtables-py#55]
JSON Table Schema defines several [constraints](http://dataprotocols.org/json-table-schema/#field-constraints) (`minLength`, `maxLength`, `pattern`, `minimum`, `maximum`, and `oneOf`) that are not yet implemented by goodtables. Goodtables should throw warnings until these are implemented (see #54). But long-term, these constraints should also be implemented.

**Comment by pwalsh** [comment]
Point taken. We implemented all commonly used parts of the spec first. 

Most of the implementation occurs in [JTSKit](https://github.com/okfn/jtskit-py), which was developed alongside goodtables. We have some issues open there for implementing the rest of the spec [JTSKit Issues](https://github.com/okfn/jtskit-py/issues), and any help would be appreciated. 

Some things (e.g: `oneOf`) are brand new (I added it to the JTS spec a week or two ago), but certainly the goal of JTSKit is to ctahc up to the current state of the spec, and remain in-step with it as it changes.

**Comment by pwalsh** [comment]
What this now actually requires is to use methods in https://github.com/frictionlessdata/jsontableschema-py that now exist, which did not exist when I originally wrote both libs together. The code here performs some of the "jts stuff" directly, and that can now be removed and replaced with those new methods.

**Comment by georgiana-b** [comment]
Can someone familiar with both GoodTables and jsontableschema-py give an example? I count identify functionality that appears in both.

**Comment by pwalsh** [comment]
@georgiana-b I'm unassigning this for now.

**Comment by roll** [comment]
Fixed in https://github.com/frictionlessdata/goodtables-py/tree/next 

`next` will be merged onto `master` soon.
