### ISSUE TITLE
Add support for tabular data packages

### ISSUE THREAD

**Issue by augusto-herrmann** [frictionlessdata/goodtables-py#66]
It would be very useful to be able to check for validity of [tabular data packages](http://dataprotocols.org/tabular-data-package/) by using the goodtables CLI. Ideally it should:
* *schema validation*: check whether the included `datapackage.json` file conforms to the tabular data package specification
  * consequently, as that is an extension of the [data package specification](http://dataprotocols.org/data-packages/), it must conform to that as well
  * check if the included schema conforms to [json table schema](http://dataprotocols.org/json-table-schema/) specification
* *data validation*: check if the resources described in it exist, are csv files and the data conforms to the [json table schema](http://dataprotocols.org/json-table-schema/) included in the `datapackage.json`

Note: this idea originated from a discussion of issue [#73](https://github.com/okfn/publicbodies/issues/73) of [publicbodies](https://github.com/okfn/publicbodies).

**Comment by pwalsh** [comment]
Hi @augusto-herrmann yes and we've discussed this very thing recently. Using the `pipeline.Batch` class you can almost do it now, but we will certainly iterate on the API for this use case soon. Meanwhile, you can:

* Use https://github.com/okfn/datapackage-validate-py to validate a `datapackage.json` descriptor, as per your first point
* Use the batch processor with a data package source to check all resources in a data package: https://github.com/okfn/goodtables/blob/master/goodtables/pipeline/batch.py#L28

Also, if you wouldn't mind, please do share with us your use case(s) so that we keep them in mind for the design of a proper treatment of this feature soon.

**Comment by augusto-herrmann** [comment]
Thanks for the tip, @pwalsh.

Where should we write use cases for goodtables? Right here on the issue tracker?

**Comment by pwalsh** [comment]
Yes! That would be great.

**Comment by pwalsh** [comment]
@augusto-herrmann would love to see your use cases. We are now doing a round of work on GoodTables, so this is a good time to get this in.

**Comment by roll** [comment]
# goodtables.next

## Invalid meta

There is no `name` in datapackage descriptor.

```bash
$ python -m goodtables.cli datapackage tmp/issue66.json

DATASET
=======
{'error-count': 1, 'table-count': 0, 'time': 0.017, 'valid': False}
---------
[-,-] [datapackage-error] 'name' is a required property
```

## Invalid data

```bash
$ python -m goodtables.cli datapackage data/datapackages/invalid/datapackage.json

DATASET
=======
{'error-count': 2, 'table-count': 2, 'time': 0.039, 'valid': False}

TABLE [1]
=========
{'datapackage': 'testing',
 'error-count': 1,
 'headers': ['id', 'name', 'description', 'amount'],
 'resource': 'data',
 'row-count': 4,
 'time': 0.015,
 'valid': False}
---------
[3,-] [blank-row] Row 3 is completely blank

TABLE [2]
=========
{'datapackage': 'testing',
 'error-count': 1,
 'headers': ['parent', 'comment'],
 'resource': 'data2',
 'row-count': 5,
 'time': 0.016,
 'valid': False}
---------
[4,-] [blank-row] Row 4 is completely blank
```

**Comment by pwalsh** [comment]
Fixed in https://github.com/frictionlessdata/goodtables-py/tree/next 

`next` will be tested for several weeks now before we merge onto `master`.
