### ISSUE TITLE
Provide more detailed information when reading inconformant schema models

### ISSUE THREAD

**Issue by augusto-herrmann** [frictionlessdata/goodtables-py#67]
When reading a schema that does not conform to specification, goodtables currently [just raises an InvalidSchemaError exception](https://github.com/okfn/goodtables/blob/master/goodtables/processors/schema.py#L91), but does not provide useful information on why it failed to validate (e.g. line numbers and position, reason for failure, etc.).

As an example:

```
$ goodtables schema examples/valid.csv --schema examples/schema_invalid_pk_array.json
...
  File "./local/lib/python2.7/site-packages/goodtables/processors/schema.py", line 91, in schema_model
    raise e
jsontableschema.exceptions.InvalidSchemaError
```
The error message should instead be something more useful like:
```
examples/schema_invalid_pk_array.json:14
 "primaryKey": ["id", "titel"]
                      ^
Invalid schema: reference to non-existing field name "titel".
```

**Comment by pwalsh** [comment]
Thanks, nice idea.

**Comment by roll** [comment]
# goodtables.next

```bash
$ python -m goodtables.cli table tmp/issue67.csv --schema tmp/issue67.json

DATASET
=======
{'error-count': 1, 'table-count': 0, 'time': 0.006, 'valid': False}
---------
[-,-] [jsontableschema-error] 'fields' is a required property
```

**Comment by pwalsh** [comment]
Fixed in https://github.com/frictionlessdata/goodtables-py/tree/next 

`next` will be tested for several weeks now before we merge onto `master`.
