### ISSUE TITLE
Update management tools

### ISSUE THREAD

**Issue by roll** [frictionlessdata/goodtables-py#75]
- [ ] https://github.com/okfn/oki-py compliance
- [ ] versioned milestones instead of `Current` (@pwalsh WDYT? - for semver and our tagged publication model it looks more appropriate for me). Example - https://github.com/frictionlessdata/tabulator-py/milestones

**Comment by pwalsh** [comment]
This lib won't be updated for compliance with coding standards now. It will happen for v1 when we rebase this on Tabulator. 

For versioned milestones, yes, most of the projects i was coding myself until ~ 6 months ago do follow such a pattern. Let's implement that as a best practice.

**Comment by pwalsh** [comment]
Fixed in https://github.com/frictionlessdata/goodtables-py/tree/next 

`next` will be tested for several weeks now before we merge onto `master`.
