### ISSUE TITLE
If JTS field names differ from column names then columns are not validated

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/goodtables-py#94]
e.g. column named "Number" and JTS has " Number" then number column is ignored.

Qu: Why do we even use column names vs JTS names - can't we use JTS order in checking or is the idea we could validate arbitrary JSON data?

**Comment by roll** [comment]
@rgrp 
Could you please explain this error (cc @pwalsh)

**Comment by rgrp** [comment]
@roll note that second Number has a space in front of it. Point is that if schema and data have different col names then column gets ignored.

**Comment by roll** [comment]
@rgrp 
Thanks! I've created a meta thread for tracking this problem - #123 (closing this issue as absorbed)
