### ISSUE TITLE
CSV incorectly split into columns

### ISSUE THREAD

**Issue by georgiana-b** [frictionlessdata/goodtables-py#98]
[This CSV](http://goodtables.okfnlabs.org/reports?data_url=https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/252886/July_2013_GPC_Transparency_Data.csv&format=CSV&encoding=&schema_url=https://raw.githubusercontent.com/okfn/tabular-validator/master/examples/hmt/spend-publishing-schema.json) seems to be incorrectly parsed. Investigate the issue.

**Comment by roll** [comment]
@georgiana-b 
Do we still have an incorrect behaviour here?

http://goodtables.okfnlabs.org/reports?data_url=https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/252886/July_2013_GPC_Transparency_Data.csv&format=CSV&encoding=&schema_url=https://raw.githubusercontent.com/okfn/tabular-validator/master/examples/hmt/spend-publishing-schema.json

**Comment by pwalsh** [comment]
@roll if this acts correctly in v1 I am happy to close this.

**Comment by roll** [comment]
```bash
$ goodtables table https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/252886/July_2013_GPC_Transparency_Data.csv
DATASET
=======
{'error-count': 9, 'table-count': 1, 'time': 0.988, 'valid': False}

TABLE [1]
=========
{'error-count': 9,
 'headers': ['Transaction reference number',
             'Posting Date',
             'Merchant Name',
             'Final Transaction Amount',
             'Description',
             '',
             '',
             '',
             ''],
 'row-count': 26,
 'time': 0.982,
 'valid': False}
---------
[-,6] [blank-header] Header in column 6 is blank
[-,7] [blank-header] Header in column 7 is blank
[-,8] [blank-header] Header in column 8 is blank
[-,9] [blank-header] Header in column 9 is blank
[-,7] [duplicate-header] Header in column 7 is duplicated to header in column(s) 6
[-,8] [duplicate-header] Header in column 8 is duplicated to header in column(s) 6, 7
[-,9] [duplicate-header] Header in column 9 is duplicated to header in column(s) 6, 7, 8
[24,-] [blank-row] Row 24 is completely blank
[25,-] [blank-row] Row 25 is completely blank
```

**Comment by roll** [comment]
I don't see any problems with this file.

**Comment by abhiravbansal** [comment]
Hi,

I believe I am facing a similar issue - CSV incorrectly split into columns #98 issue.

If am validating attached file (testing.xlsx) - is it passing through Good tables.

However, if I am validating each column separately (single.column.xlsx) - it is splitting into multiple columns. This is the case with each column of testing.csv.

[testing.xlsx](https://github.com/frictionlessdata/goodtables-py/files/1083480/testing.xlsx)
[single column.xlsx](https://github.com/frictionlessdata/goodtables-py/files/1083481/single.column.xlsx)

**Comment by roll** [comment]
@abhiravbansal 
Could you please write `goodtables-py` version you use.

**Comment by roll** [comment]
@abhiravbansal 
I've tested with the latest `goodtables==1.0.0a16` and it seems working as excreted:

```
$ goodtables table testing.xlsx
DATASET
=======
{'error-count': 532, 'table-count': 1, 'time': 0.374, 'valid': False}
---------
Warning: Table "/home/roll/testing.xlsx" inspection has reached 1000 row(s) limit

TABLE [1]
=========
{'error-count': 532,
 'headers': ['Model',
             'Colour',
             'Fuel Type',
             'TARE Weight (Kg)',
             'VIN (Prefix only)'],
 'row-count': 1000,
 'source': '/home/roll/testing.xlsx',
 'time': 0.372,
 'valid': False}
``` 

and

```
$ goodtables table single.column.xlsx
DATASET
=======
{'error-count': 725, 'table-count': 1, 'time': 0.306, 'valid': False}
---------
Warning: Table "/home/roll/single.column.xlsx" inspection has reached 1000 row(s) limit

TABLE [1]
=========
{'error-count': 725,
 'headers': ['Model'],
 'row-count': 1000,
 'source': '/home/roll/single.column.xlsx',
 'time': 0.304,
 'valid': False}
```

**Comment by roll** [comment]
Please re-open if issue still exists.

**Comment by abhiravbansal** [comment]
Hi,
Thanks for your help and support, appreciated. Unfortunately the issue persists. I am attaching screenshot of the error message.

Thanks mate :)

![error msg_2017-06-20 10_20_20-good tables](https://user-images.githubusercontent.com/29526768/27311239-f851ea26-55a2-11e7-9fbb-b0523c9b6af6.png)

**Comment by abhiravbansal** [comment]
Also, below is the JSON schema which am using for this.

{
   "fields": [
      {
         "name": "Fuel type",
         "title": "fuel type of the vehicle",
         "description": "Refers to the fuel type of the vehicle",
         "type": "string",
         "format": "default",
         "constraints": {
            "enum": [
               "PETROL",
               "ELECTRIC",
               "KEROSENE",
               "PETROL AND GAS",
               "PETROL AND ELECTRIC",
               "DIESEL"
            ],
            "required": true
         }
      }
   ]
}
